// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "travelohi/v1/hotel/hotel.proto" (package "travelohi.v1.hotel", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message travelohi.v1.hotel.Hotel
 */
export interface Hotel {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string name = 2
     */
    name: string;
    /**
     * @generated from protobuf field: string description = 3
     */
    description: string;
    /**
     * @generated from protobuf field: string address = 4
     */
    address: string;
    /**
     * @generated from protobuf field: repeated string picture_urls = 5
     */
    pictureUrls: string[];
    /**
     * @generated from protobuf field: repeated string facilities = 6
     */
    facilities: string[]; // e.g., "Swimming Pool", "WiFi"
    /**
     * @generated from protobuf field: float rating_cleanliness = 7
     */
    ratingCleanliness: number;
    /**
     * @generated from protobuf field: float rating_comfort = 8
     */
    ratingComfort: number;
    /**
     * @generated from protobuf field: float rating_location = 9
     */
    ratingLocation: number;
    /**
     * @generated from protobuf field: float rating_service = 10
     */
    ratingService: number;
    /**
     * @generated from protobuf field: float rating_average = 11
     */
    ratingAverage: number;
    /**
     * @generated from protobuf field: int32 total_reviews = 12
     */
    totalReviews: number;
    /**
     * @generated from protobuf field: int64 starting_price = 13
     */
    startingPrice: bigint;
    /**
     * @generated from protobuf field: int32 availability = 14
     */
    availability: number;
}
/**
 * @generated from protobuf message travelohi.v1.hotel.HotelRoom
 */
export interface HotelRoom {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string hotel_id = 2
     */
    hotelId: string;
    /**
     * @generated from protobuf field: string name = 3
     */
    name: string; // e.g., "Deluxe King"
    /**
     * @generated from protobuf field: int64 price_per_night = 4
     */
    pricePerNight: bigint;
    /**
     * @generated from protobuf field: int32 capacity = 5
     */
    capacity: number;
    /**
     * @generated from protobuf field: repeated string facilities = 6
     */
    facilities: string[]; // e.g., "Bathtub", "Non-smoking"
    /**
     * @generated from protobuf field: int32 available_count = 7
     */
    availableCount: number;
    /**
     * @generated from protobuf field: string image_url = 8
     */
    imageUrl: string;
}
/**
 * @generated from protobuf message travelohi.v1.hotel.HotelReview
 */
export interface HotelReview {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string hotel_id = 2
     */
    hotelId: string;
    /**
     * @generated from protobuf field: string user_id = 3
     */
    userId: string;
    /**
     * @generated from protobuf field: string user_name = 4
     */
    userName: string;
    /**
     * @generated from protobuf field: float rating_cleanliness = 5
     */
    ratingCleanliness: number;
    /**
     * @generated from protobuf field: float rating_comfort = 6
     */
    ratingComfort: number;
    /**
     * @generated from protobuf field: float rating_location = 7
     */
    ratingLocation: number;
    /**
     * @generated from protobuf field: float rating_service = 8
     */
    ratingService: number;
    /**
     * @generated from protobuf field: float rating_average = 9
     */
    ratingAverage: number;
    /**
     * @generated from protobuf field: string comment = 10
     */
    comment: string;
    /**
     * @generated from protobuf field: string created_at = 11
     */
    createdAt: string;
}
/**
 * @generated from protobuf message travelohi.v1.hotel.SearchHotelsRequest
 */
export interface SearchHotelsRequest {
    /**
     * @generated from protobuf field: string query = 1
     */
    query: string; // name/city
    /**
     * @generated from protobuf field: string check_in_date = 2
     */
    checkInDate: string;
    /**
     * @generated from protobuf field: string check_out_date = 3
     */
    checkOutDate: string;
    /**
     * filter related
     *
     * @generated from protobuf field: int64 min_price = 4
     */
    minPrice: bigint;
    /**
     * @generated from protobuf field: int64 max_price = 5
     */
    maxPrice: bigint;
    /**
     * @generated from protobuf field: float min_rating = 6
     */
    minRating: number;
    /**
     * @generated from protobuf field: repeated string facilities = 7
     */
    facilities: string[];
    /**
     * sort, pagination
     *
     * @generated from protobuf field: string sort_by = 8
     */
    sortBy: string; // "rating", "price", "reviews", "availability"
    /**
     * @generated from protobuf field: string sort_order = 9
     */
    sortOrder: string; // "asc", "desc"
    /**
     * @generated from protobuf field: int32 limit = 10
     */
    limit: number; // Must be 20, 25, or 30
    /**
     * @generated from protobuf field: int32 offset = 11
     */
    offset: number;
}
/**
 * @generated from protobuf message travelohi.v1.hotel.SearchHotelsResponse
 */
export interface SearchHotelsResponse {
    /**
     * @generated from protobuf field: repeated travelohi.v1.hotel.Hotel hotels = 1
     */
    hotels: Hotel[];
    /**
     * @generated from protobuf field: int32 total_results = 2
     */
    totalResults: number;
}
/**
 * @generated from protobuf message travelohi.v1.hotel.GetHotelDetailsRequest
 */
export interface GetHotelDetailsRequest {
    /**
     * @generated from protobuf field: string hotel_id = 1
     */
    hotelId: string;
    /**
     * @generated from protobuf field: string check_in_date = 2
     */
    checkInDate: string;
    /**
     * @generated from protobuf field: string check_out_date = 3
     */
    checkOutDate: string;
}
/**
 * @generated from protobuf message travelohi.v1.hotel.GetHotelDetailsResponse
 */
export interface GetHotelDetailsResponse {
    /**
     * @generated from protobuf field: travelohi.v1.hotel.Hotel hotel = 1
     */
    hotel?: Hotel;
    /**
     * @generated from protobuf field: repeated travelohi.v1.hotel.HotelRoom available_rooms = 2
     */
    availableRooms: HotelRoom[];
    /**
     * @generated from protobuf field: repeated travelohi.v1.hotel.HotelReview recent_reviews = 3
     */
    recentReviews: HotelReview[];
}
/**
 * @generated from protobuf message travelohi.v1.hotel.AddHotelReviewRequest
 */
export interface AddHotelReviewRequest {
    /**
     * @generated from protobuf field: string hotel_id = 1
     */
    hotelId: string;
    /**
     * @generated from protobuf field: float rating_cleanliness = 2
     */
    ratingCleanliness: number;
    /**
     * @generated from protobuf field: float rating_comfort = 3
     */
    ratingComfort: number;
    /**
     * @generated from protobuf field: float rating_location = 4
     */
    ratingLocation: number;
    /**
     * @generated from protobuf field: float rating_service = 5
     */
    ratingService: number;
    /**
     * @generated from protobuf field: string comment = 6
     */
    comment: string;
    /**
     * @generated from protobuf field: bool is_anonymous = 7
     */
    isAnonymous: boolean;
    /**
     * @generated from protobuf field: string booking_id = 8
     */
    bookingId: string;
    /**
     * @generated from protobuf field: string user_name = 9
     */
    userName: string;
}
/**
 * @generated from protobuf message travelohi.v1.hotel.AddHotelReviewResponse
 */
export interface AddHotelReviewResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class Hotel$Type extends MessageType<Hotel> {
    constructor() {
        super("travelohi.v1.hotel.Hotel", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "address", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "picture_urls", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "facilities", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "rating_cleanliness", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 8, name: "rating_comfort", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 9, name: "rating_location", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 10, name: "rating_service", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 11, name: "rating_average", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 12, name: "total_reviews", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 13, name: "starting_price", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 14, name: "availability", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<Hotel>): Hotel {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.name = "";
        message.description = "";
        message.address = "";
        message.pictureUrls = [];
        message.facilities = [];
        message.ratingCleanliness = 0;
        message.ratingComfort = 0;
        message.ratingLocation = 0;
        message.ratingService = 0;
        message.ratingAverage = 0;
        message.totalReviews = 0;
        message.startingPrice = 0n;
        message.availability = 0;
        if (value !== undefined)
            reflectionMergePartial<Hotel>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Hotel): Hotel {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* string description */ 3:
                    message.description = reader.string();
                    break;
                case /* string address */ 4:
                    message.address = reader.string();
                    break;
                case /* repeated string picture_urls */ 5:
                    message.pictureUrls.push(reader.string());
                    break;
                case /* repeated string facilities */ 6:
                    message.facilities.push(reader.string());
                    break;
                case /* float rating_cleanliness */ 7:
                    message.ratingCleanliness = reader.float();
                    break;
                case /* float rating_comfort */ 8:
                    message.ratingComfort = reader.float();
                    break;
                case /* float rating_location */ 9:
                    message.ratingLocation = reader.float();
                    break;
                case /* float rating_service */ 10:
                    message.ratingService = reader.float();
                    break;
                case /* float rating_average */ 11:
                    message.ratingAverage = reader.float();
                    break;
                case /* int32 total_reviews */ 12:
                    message.totalReviews = reader.int32();
                    break;
                case /* int64 starting_price */ 13:
                    message.startingPrice = reader.int64().toBigInt();
                    break;
                case /* int32 availability */ 14:
                    message.availability = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Hotel, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* string description = 3; */
        if (message.description !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.description);
        /* string address = 4; */
        if (message.address !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.address);
        /* repeated string picture_urls = 5; */
        for (let i = 0; i < message.pictureUrls.length; i++)
            writer.tag(5, WireType.LengthDelimited).string(message.pictureUrls[i]);
        /* repeated string facilities = 6; */
        for (let i = 0; i < message.facilities.length; i++)
            writer.tag(6, WireType.LengthDelimited).string(message.facilities[i]);
        /* float rating_cleanliness = 7; */
        if (message.ratingCleanliness !== 0)
            writer.tag(7, WireType.Bit32).float(message.ratingCleanliness);
        /* float rating_comfort = 8; */
        if (message.ratingComfort !== 0)
            writer.tag(8, WireType.Bit32).float(message.ratingComfort);
        /* float rating_location = 9; */
        if (message.ratingLocation !== 0)
            writer.tag(9, WireType.Bit32).float(message.ratingLocation);
        /* float rating_service = 10; */
        if (message.ratingService !== 0)
            writer.tag(10, WireType.Bit32).float(message.ratingService);
        /* float rating_average = 11; */
        if (message.ratingAverage !== 0)
            writer.tag(11, WireType.Bit32).float(message.ratingAverage);
        /* int32 total_reviews = 12; */
        if (message.totalReviews !== 0)
            writer.tag(12, WireType.Varint).int32(message.totalReviews);
        /* int64 starting_price = 13; */
        if (message.startingPrice !== 0n)
            writer.tag(13, WireType.Varint).int64(message.startingPrice);
        /* int32 availability = 14; */
        if (message.availability !== 0)
            writer.tag(14, WireType.Varint).int32(message.availability);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.hotel.Hotel
 */
export const Hotel = new Hotel$Type();
// @generated message type with reflection information, may provide speed optimized methods
class HotelRoom$Type extends MessageType<HotelRoom> {
    constructor() {
        super("travelohi.v1.hotel.HotelRoom", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "hotel_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "price_per_night", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 5, name: "capacity", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "facilities", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "available_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 8, name: "image_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<HotelRoom>): HotelRoom {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.hotelId = "";
        message.name = "";
        message.pricePerNight = 0n;
        message.capacity = 0;
        message.facilities = [];
        message.availableCount = 0;
        message.imageUrl = "";
        if (value !== undefined)
            reflectionMergePartial<HotelRoom>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: HotelRoom): HotelRoom {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string hotel_id */ 2:
                    message.hotelId = reader.string();
                    break;
                case /* string name */ 3:
                    message.name = reader.string();
                    break;
                case /* int64 price_per_night */ 4:
                    message.pricePerNight = reader.int64().toBigInt();
                    break;
                case /* int32 capacity */ 5:
                    message.capacity = reader.int32();
                    break;
                case /* repeated string facilities */ 6:
                    message.facilities.push(reader.string());
                    break;
                case /* int32 available_count */ 7:
                    message.availableCount = reader.int32();
                    break;
                case /* string image_url */ 8:
                    message.imageUrl = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: HotelRoom, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string hotel_id = 2; */
        if (message.hotelId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.hotelId);
        /* string name = 3; */
        if (message.name !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.name);
        /* int64 price_per_night = 4; */
        if (message.pricePerNight !== 0n)
            writer.tag(4, WireType.Varint).int64(message.pricePerNight);
        /* int32 capacity = 5; */
        if (message.capacity !== 0)
            writer.tag(5, WireType.Varint).int32(message.capacity);
        /* repeated string facilities = 6; */
        for (let i = 0; i < message.facilities.length; i++)
            writer.tag(6, WireType.LengthDelimited).string(message.facilities[i]);
        /* int32 available_count = 7; */
        if (message.availableCount !== 0)
            writer.tag(7, WireType.Varint).int32(message.availableCount);
        /* string image_url = 8; */
        if (message.imageUrl !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.imageUrl);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.hotel.HotelRoom
 */
export const HotelRoom = new HotelRoom$Type();
// @generated message type with reflection information, may provide speed optimized methods
class HotelReview$Type extends MessageType<HotelReview> {
    constructor() {
        super("travelohi.v1.hotel.HotelReview", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "hotel_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "user_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "rating_cleanliness", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 6, name: "rating_comfort", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 7, name: "rating_location", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 8, name: "rating_service", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 9, name: "rating_average", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 10, name: "comment", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 11, name: "created_at", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<HotelReview>): HotelReview {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.hotelId = "";
        message.userId = "";
        message.userName = "";
        message.ratingCleanliness = 0;
        message.ratingComfort = 0;
        message.ratingLocation = 0;
        message.ratingService = 0;
        message.ratingAverage = 0;
        message.comment = "";
        message.createdAt = "";
        if (value !== undefined)
            reflectionMergePartial<HotelReview>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: HotelReview): HotelReview {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string hotel_id */ 2:
                    message.hotelId = reader.string();
                    break;
                case /* string user_id */ 3:
                    message.userId = reader.string();
                    break;
                case /* string user_name */ 4:
                    message.userName = reader.string();
                    break;
                case /* float rating_cleanliness */ 5:
                    message.ratingCleanliness = reader.float();
                    break;
                case /* float rating_comfort */ 6:
                    message.ratingComfort = reader.float();
                    break;
                case /* float rating_location */ 7:
                    message.ratingLocation = reader.float();
                    break;
                case /* float rating_service */ 8:
                    message.ratingService = reader.float();
                    break;
                case /* float rating_average */ 9:
                    message.ratingAverage = reader.float();
                    break;
                case /* string comment */ 10:
                    message.comment = reader.string();
                    break;
                case /* string created_at */ 11:
                    message.createdAt = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: HotelReview, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string hotel_id = 2; */
        if (message.hotelId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.hotelId);
        /* string user_id = 3; */
        if (message.userId !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.userId);
        /* string user_name = 4; */
        if (message.userName !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.userName);
        /* float rating_cleanliness = 5; */
        if (message.ratingCleanliness !== 0)
            writer.tag(5, WireType.Bit32).float(message.ratingCleanliness);
        /* float rating_comfort = 6; */
        if (message.ratingComfort !== 0)
            writer.tag(6, WireType.Bit32).float(message.ratingComfort);
        /* float rating_location = 7; */
        if (message.ratingLocation !== 0)
            writer.tag(7, WireType.Bit32).float(message.ratingLocation);
        /* float rating_service = 8; */
        if (message.ratingService !== 0)
            writer.tag(8, WireType.Bit32).float(message.ratingService);
        /* float rating_average = 9; */
        if (message.ratingAverage !== 0)
            writer.tag(9, WireType.Bit32).float(message.ratingAverage);
        /* string comment = 10; */
        if (message.comment !== "")
            writer.tag(10, WireType.LengthDelimited).string(message.comment);
        /* string created_at = 11; */
        if (message.createdAt !== "")
            writer.tag(11, WireType.LengthDelimited).string(message.createdAt);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.hotel.HotelReview
 */
export const HotelReview = new HotelReview$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SearchHotelsRequest$Type extends MessageType<SearchHotelsRequest> {
    constructor() {
        super("travelohi.v1.hotel.SearchHotelsRequest", [
            { no: 1, name: "query", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "check_in_date", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "check_out_date", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "min_price", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 5, name: "max_price", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 6, name: "min_rating", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 7, name: "facilities", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "sort_by", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "sort_order", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "limit", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 11, name: "offset", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<SearchHotelsRequest>): SearchHotelsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.query = "";
        message.checkInDate = "";
        message.checkOutDate = "";
        message.minPrice = 0n;
        message.maxPrice = 0n;
        message.minRating = 0;
        message.facilities = [];
        message.sortBy = "";
        message.sortOrder = "";
        message.limit = 0;
        message.offset = 0;
        if (value !== undefined)
            reflectionMergePartial<SearchHotelsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SearchHotelsRequest): SearchHotelsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string query */ 1:
                    message.query = reader.string();
                    break;
                case /* string check_in_date */ 2:
                    message.checkInDate = reader.string();
                    break;
                case /* string check_out_date */ 3:
                    message.checkOutDate = reader.string();
                    break;
                case /* int64 min_price */ 4:
                    message.minPrice = reader.int64().toBigInt();
                    break;
                case /* int64 max_price */ 5:
                    message.maxPrice = reader.int64().toBigInt();
                    break;
                case /* float min_rating */ 6:
                    message.minRating = reader.float();
                    break;
                case /* repeated string facilities */ 7:
                    message.facilities.push(reader.string());
                    break;
                case /* string sort_by */ 8:
                    message.sortBy = reader.string();
                    break;
                case /* string sort_order */ 9:
                    message.sortOrder = reader.string();
                    break;
                case /* int32 limit */ 10:
                    message.limit = reader.int32();
                    break;
                case /* int32 offset */ 11:
                    message.offset = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SearchHotelsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string query = 1; */
        if (message.query !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.query);
        /* string check_in_date = 2; */
        if (message.checkInDate !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.checkInDate);
        /* string check_out_date = 3; */
        if (message.checkOutDate !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.checkOutDate);
        /* int64 min_price = 4; */
        if (message.minPrice !== 0n)
            writer.tag(4, WireType.Varint).int64(message.minPrice);
        /* int64 max_price = 5; */
        if (message.maxPrice !== 0n)
            writer.tag(5, WireType.Varint).int64(message.maxPrice);
        /* float min_rating = 6; */
        if (message.minRating !== 0)
            writer.tag(6, WireType.Bit32).float(message.minRating);
        /* repeated string facilities = 7; */
        for (let i = 0; i < message.facilities.length; i++)
            writer.tag(7, WireType.LengthDelimited).string(message.facilities[i]);
        /* string sort_by = 8; */
        if (message.sortBy !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.sortBy);
        /* string sort_order = 9; */
        if (message.sortOrder !== "")
            writer.tag(9, WireType.LengthDelimited).string(message.sortOrder);
        /* int32 limit = 10; */
        if (message.limit !== 0)
            writer.tag(10, WireType.Varint).int32(message.limit);
        /* int32 offset = 11; */
        if (message.offset !== 0)
            writer.tag(11, WireType.Varint).int32(message.offset);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.hotel.SearchHotelsRequest
 */
export const SearchHotelsRequest = new SearchHotelsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SearchHotelsResponse$Type extends MessageType<SearchHotelsResponse> {
    constructor() {
        super("travelohi.v1.hotel.SearchHotelsResponse", [
            { no: 1, name: "hotels", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Hotel },
            { no: 2, name: "total_results", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<SearchHotelsResponse>): SearchHotelsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.hotels = [];
        message.totalResults = 0;
        if (value !== undefined)
            reflectionMergePartial<SearchHotelsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SearchHotelsResponse): SearchHotelsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated travelohi.v1.hotel.Hotel hotels */ 1:
                    message.hotels.push(Hotel.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* int32 total_results */ 2:
                    message.totalResults = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SearchHotelsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated travelohi.v1.hotel.Hotel hotels = 1; */
        for (let i = 0; i < message.hotels.length; i++)
            Hotel.internalBinaryWrite(message.hotels[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* int32 total_results = 2; */
        if (message.totalResults !== 0)
            writer.tag(2, WireType.Varint).int32(message.totalResults);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.hotel.SearchHotelsResponse
 */
export const SearchHotelsResponse = new SearchHotelsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetHotelDetailsRequest$Type extends MessageType<GetHotelDetailsRequest> {
    constructor() {
        super("travelohi.v1.hotel.GetHotelDetailsRequest", [
            { no: 1, name: "hotel_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "check_in_date", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "check_out_date", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetHotelDetailsRequest>): GetHotelDetailsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.hotelId = "";
        message.checkInDate = "";
        message.checkOutDate = "";
        if (value !== undefined)
            reflectionMergePartial<GetHotelDetailsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetHotelDetailsRequest): GetHotelDetailsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string hotel_id */ 1:
                    message.hotelId = reader.string();
                    break;
                case /* string check_in_date */ 2:
                    message.checkInDate = reader.string();
                    break;
                case /* string check_out_date */ 3:
                    message.checkOutDate = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetHotelDetailsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string hotel_id = 1; */
        if (message.hotelId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.hotelId);
        /* string check_in_date = 2; */
        if (message.checkInDate !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.checkInDate);
        /* string check_out_date = 3; */
        if (message.checkOutDate !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.checkOutDate);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.hotel.GetHotelDetailsRequest
 */
export const GetHotelDetailsRequest = new GetHotelDetailsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetHotelDetailsResponse$Type extends MessageType<GetHotelDetailsResponse> {
    constructor() {
        super("travelohi.v1.hotel.GetHotelDetailsResponse", [
            { no: 1, name: "hotel", kind: "message", T: () => Hotel },
            { no: 2, name: "available_rooms", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => HotelRoom },
            { no: 3, name: "recent_reviews", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => HotelReview }
        ]);
    }
    create(value?: PartialMessage<GetHotelDetailsResponse>): GetHotelDetailsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.availableRooms = [];
        message.recentReviews = [];
        if (value !== undefined)
            reflectionMergePartial<GetHotelDetailsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetHotelDetailsResponse): GetHotelDetailsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* travelohi.v1.hotel.Hotel hotel */ 1:
                    message.hotel = Hotel.internalBinaryRead(reader, reader.uint32(), options, message.hotel);
                    break;
                case /* repeated travelohi.v1.hotel.HotelRoom available_rooms */ 2:
                    message.availableRooms.push(HotelRoom.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated travelohi.v1.hotel.HotelReview recent_reviews */ 3:
                    message.recentReviews.push(HotelReview.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetHotelDetailsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* travelohi.v1.hotel.Hotel hotel = 1; */
        if (message.hotel)
            Hotel.internalBinaryWrite(message.hotel, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* repeated travelohi.v1.hotel.HotelRoom available_rooms = 2; */
        for (let i = 0; i < message.availableRooms.length; i++)
            HotelRoom.internalBinaryWrite(message.availableRooms[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* repeated travelohi.v1.hotel.HotelReview recent_reviews = 3; */
        for (let i = 0; i < message.recentReviews.length; i++)
            HotelReview.internalBinaryWrite(message.recentReviews[i], writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.hotel.GetHotelDetailsResponse
 */
export const GetHotelDetailsResponse = new GetHotelDetailsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AddHotelReviewRequest$Type extends MessageType<AddHotelReviewRequest> {
    constructor() {
        super("travelohi.v1.hotel.AddHotelReviewRequest", [
            { no: 1, name: "hotel_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "rating_cleanliness", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 3, name: "rating_comfort", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 4, name: "rating_location", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 5, name: "rating_service", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 6, name: "comment", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "is_anonymous", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 8, name: "booking_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "user_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<AddHotelReviewRequest>): AddHotelReviewRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.hotelId = "";
        message.ratingCleanliness = 0;
        message.ratingComfort = 0;
        message.ratingLocation = 0;
        message.ratingService = 0;
        message.comment = "";
        message.isAnonymous = false;
        message.bookingId = "";
        message.userName = "";
        if (value !== undefined)
            reflectionMergePartial<AddHotelReviewRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AddHotelReviewRequest): AddHotelReviewRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string hotel_id */ 1:
                    message.hotelId = reader.string();
                    break;
                case /* float rating_cleanliness */ 2:
                    message.ratingCleanliness = reader.float();
                    break;
                case /* float rating_comfort */ 3:
                    message.ratingComfort = reader.float();
                    break;
                case /* float rating_location */ 4:
                    message.ratingLocation = reader.float();
                    break;
                case /* float rating_service */ 5:
                    message.ratingService = reader.float();
                    break;
                case /* string comment */ 6:
                    message.comment = reader.string();
                    break;
                case /* bool is_anonymous */ 7:
                    message.isAnonymous = reader.bool();
                    break;
                case /* string booking_id */ 8:
                    message.bookingId = reader.string();
                    break;
                case /* string user_name */ 9:
                    message.userName = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AddHotelReviewRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string hotel_id = 1; */
        if (message.hotelId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.hotelId);
        /* float rating_cleanliness = 2; */
        if (message.ratingCleanliness !== 0)
            writer.tag(2, WireType.Bit32).float(message.ratingCleanliness);
        /* float rating_comfort = 3; */
        if (message.ratingComfort !== 0)
            writer.tag(3, WireType.Bit32).float(message.ratingComfort);
        /* float rating_location = 4; */
        if (message.ratingLocation !== 0)
            writer.tag(4, WireType.Bit32).float(message.ratingLocation);
        /* float rating_service = 5; */
        if (message.ratingService !== 0)
            writer.tag(5, WireType.Bit32).float(message.ratingService);
        /* string comment = 6; */
        if (message.comment !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.comment);
        /* bool is_anonymous = 7; */
        if (message.isAnonymous !== false)
            writer.tag(7, WireType.Varint).bool(message.isAnonymous);
        /* string booking_id = 8; */
        if (message.bookingId !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.bookingId);
        /* string user_name = 9; */
        if (message.userName !== "")
            writer.tag(9, WireType.LengthDelimited).string(message.userName);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.hotel.AddHotelReviewRequest
 */
export const AddHotelReviewRequest = new AddHotelReviewRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AddHotelReviewResponse$Type extends MessageType<AddHotelReviewResponse> {
    constructor() {
        super("travelohi.v1.hotel.AddHotelReviewResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<AddHotelReviewResponse>): AddHotelReviewResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<AddHotelReviewResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AddHotelReviewResponse): AddHotelReviewResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AddHotelReviewResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.hotel.AddHotelReviewResponse
 */
export const AddHotelReviewResponse = new AddHotelReviewResponse$Type();
/**
 * @generated ServiceType for protobuf service travelohi.v1.hotel.HotelService
 */
export const HotelService = new ServiceType("travelohi.v1.hotel.HotelService", [
    { name: "SearchHotels", options: {}, I: SearchHotelsRequest, O: SearchHotelsResponse },
    { name: "GetHotelDetails", options: {}, I: GetHotelDetailsRequest, O: GetHotelDetailsResponse },
    { name: "AddHotelReview", options: {}, I: AddHotelReviewRequest, O: AddHotelReviewResponse }
]);
