# Dockerfile.protoc
FROM golang:1.26.0-alpine

RUN apk add --no-cache protobuf nodejs npm

RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
RUN npm install -g @protobuf-ts/plugin@latest

ENV PATH="$PATH:/go/bin"

WORKDIR /workspace