// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.31.1
// source: proto/travelohi/v1/telemetry/telemetry.proto

package telemetrypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TelemetryService_LogSearchQuery_FullMethodName               = "/travelohi.v1.telemetry.TelemetryService/LogSearchQuery"
	TelemetryService_GetRecentSearches_FullMethodName            = "/travelohi.v1.telemetry.TelemetryService/GetRecentSearches"
	TelemetryService_GetGlobalRecommendations_FullMethodName     = "/travelohi.v1.telemetry.TelemetryService/GetGlobalRecommendations"
	TelemetryService_GetPopularFlightDestinations_FullMethodName = "/travelohi.v1.telemetry.TelemetryService/GetPopularFlightDestinations"
	TelemetryService_GetPopularHotels_FullMethodName             = "/travelohi.v1.telemetry.TelemetryService/GetPopularHotels"
)

// TelemetryServiceClient is the client API for TelemetryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TelemetryServiceClient interface {
	// Search History Tracking
	LogSearchQuery(ctx context.Context, in *LogSearchQueryRequest, opts ...grpc.CallOption) (*TelemetryResponse, error)
	GetRecentSearches(ctx context.Context, in *GetRecentSearchesRequest, opts ...grpc.CallOption) (*GetRecentSearchesResponse, error)
	// Global Recommendations & Popularity Metrics
	GetGlobalRecommendations(ctx context.Context, in *GetGlobalRecommendationsRequest, opts ...grpc.CallOption) (*GetGlobalRecommendationsResponse, error)
	GetPopularFlightDestinations(ctx context.Context, in *GetPopularFlightsRequest, opts ...grpc.CallOption) (*GetPopularFlightsResponse, error)
	GetPopularHotels(ctx context.Context, in *GetPopularHotelsRequest, opts ...grpc.CallOption) (*GetPopularHotelsResponse, error)
}

type telemetryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTelemetryServiceClient(cc grpc.ClientConnInterface) TelemetryServiceClient {
	return &telemetryServiceClient{cc}
}

func (c *telemetryServiceClient) LogSearchQuery(ctx context.Context, in *LogSearchQueryRequest, opts ...grpc.CallOption) (*TelemetryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TelemetryResponse)
	err := c.cc.Invoke(ctx, TelemetryService_LogSearchQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryServiceClient) GetRecentSearches(ctx context.Context, in *GetRecentSearchesRequest, opts ...grpc.CallOption) (*GetRecentSearchesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRecentSearchesResponse)
	err := c.cc.Invoke(ctx, TelemetryService_GetRecentSearches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryServiceClient) GetGlobalRecommendations(ctx context.Context, in *GetGlobalRecommendationsRequest, opts ...grpc.CallOption) (*GetGlobalRecommendationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGlobalRecommendationsResponse)
	err := c.cc.Invoke(ctx, TelemetryService_GetGlobalRecommendations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryServiceClient) GetPopularFlightDestinations(ctx context.Context, in *GetPopularFlightsRequest, opts ...grpc.CallOption) (*GetPopularFlightsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPopularFlightsResponse)
	err := c.cc.Invoke(ctx, TelemetryService_GetPopularFlightDestinations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryServiceClient) GetPopularHotels(ctx context.Context, in *GetPopularHotelsRequest, opts ...grpc.CallOption) (*GetPopularHotelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPopularHotelsResponse)
	err := c.cc.Invoke(ctx, TelemetryService_GetPopularHotels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TelemetryServiceServer is the server API for TelemetryService service.
// All implementations must embed UnimplementedTelemetryServiceServer
// for forward compatibility.
type TelemetryServiceServer interface {
	// Search History Tracking
	LogSearchQuery(context.Context, *LogSearchQueryRequest) (*TelemetryResponse, error)
	GetRecentSearches(context.Context, *GetRecentSearchesRequest) (*GetRecentSearchesResponse, error)
	// Global Recommendations & Popularity Metrics
	GetGlobalRecommendations(context.Context, *GetGlobalRecommendationsRequest) (*GetGlobalRecommendationsResponse, error)
	GetPopularFlightDestinations(context.Context, *GetPopularFlightsRequest) (*GetPopularFlightsResponse, error)
	GetPopularHotels(context.Context, *GetPopularHotelsRequest) (*GetPopularHotelsResponse, error)
	mustEmbedUnimplementedTelemetryServiceServer()
}

// UnimplementedTelemetryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTelemetryServiceServer struct{}

func (UnimplementedTelemetryServiceServer) LogSearchQuery(context.Context, *LogSearchQueryRequest) (*TelemetryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LogSearchQuery not implemented")
}
func (UnimplementedTelemetryServiceServer) GetRecentSearches(context.Context, *GetRecentSearchesRequest) (*GetRecentSearchesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecentSearches not implemented")
}
func (UnimplementedTelemetryServiceServer) GetGlobalRecommendations(context.Context, *GetGlobalRecommendationsRequest) (*GetGlobalRecommendationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGlobalRecommendations not implemented")
}
func (UnimplementedTelemetryServiceServer) GetPopularFlightDestinations(context.Context, *GetPopularFlightsRequest) (*GetPopularFlightsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPopularFlightDestinations not implemented")
}
func (UnimplementedTelemetryServiceServer) GetPopularHotels(context.Context, *GetPopularHotelsRequest) (*GetPopularHotelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPopularHotels not implemented")
}
func (UnimplementedTelemetryServiceServer) mustEmbedUnimplementedTelemetryServiceServer() {}
func (UnimplementedTelemetryServiceServer) testEmbeddedByValue()                          {}

// UnsafeTelemetryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TelemetryServiceServer will
// result in compilation errors.
type UnsafeTelemetryServiceServer interface {
	mustEmbedUnimplementedTelemetryServiceServer()
}

func RegisterTelemetryServiceServer(s grpc.ServiceRegistrar, srv TelemetryServiceServer) {
	// If the following call panics, it indicates UnimplementedTelemetryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TelemetryService_ServiceDesc, srv)
}

func _TelemetryService_LogSearchQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogSearchQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryServiceServer).LogSearchQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryService_LogSearchQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryServiceServer).LogSearchQuery(ctx, req.(*LogSearchQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryService_GetRecentSearches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecentSearchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryServiceServer).GetRecentSearches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryService_GetRecentSearches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryServiceServer).GetRecentSearches(ctx, req.(*GetRecentSearchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryService_GetGlobalRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGlobalRecommendationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryServiceServer).GetGlobalRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryService_GetGlobalRecommendations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryServiceServer).GetGlobalRecommendations(ctx, req.(*GetGlobalRecommendationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryService_GetPopularFlightDestinations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPopularFlightsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryServiceServer).GetPopularFlightDestinations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryService_GetPopularFlightDestinations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryServiceServer).GetPopularFlightDestinations(ctx, req.(*GetPopularFlightsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryService_GetPopularHotels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPopularHotelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryServiceServer).GetPopularHotels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryService_GetPopularHotels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryServiceServer).GetPopularHotels(ctx, req.(*GetPopularHotelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TelemetryService_ServiceDesc is the grpc.ServiceDesc for TelemetryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TelemetryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "travelohi.v1.telemetry.TelemetryService",
	HandlerType: (*TelemetryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LogSearchQuery",
			Handler:    _TelemetryService_LogSearchQuery_Handler,
		},
		{
			MethodName: "GetRecentSearches",
			Handler:    _TelemetryService_GetRecentSearches_Handler,
		},
		{
			MethodName: "GetGlobalRecommendations",
			Handler:    _TelemetryService_GetGlobalRecommendations_Handler,
		},
		{
			MethodName: "GetPopularFlightDestinations",
			Handler:    _TelemetryService_GetPopularFlightDestinations_Handler,
		},
		{
			MethodName: "GetPopularHotels",
			Handler:    _TelemetryService_GetPopularHotels_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/travelohi/v1/telemetry/telemetry.proto",
}
