// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: proto/travelohi/v1/telemetry/telemetry.proto

package telemetrypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogSearchQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogSearchQueryRequest) Reset() {
	*x = LogSearchQueryRequest{}
	mi := &file_proto_travelohi_v1_telemetry_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogSearchQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogSearchQueryRequest) ProtoMessage() {}

func (x *LogSearchQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_travelohi_v1_telemetry_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogSearchQueryRequest.ProtoReflect.Descriptor instead.
func (*LogSearchQueryRequest) Descriptor() ([]byte, []int) {
	return file_proto_travelohi_v1_telemetry_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *LogSearchQueryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LogSearchQueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type GetRecentSearchesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecentSearchesRequest) Reset() {
	*x = GetRecentSearchesRequest{}
	mi := &file_proto_travelohi_v1_telemetry_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecentSearchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentSearchesRequest) ProtoMessage() {}

func (x *GetRecentSearchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_travelohi_v1_telemetry_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentSearchesRequest.ProtoReflect.Descriptor instead.
func (*GetRecentSearchesRequest) Descriptor() ([]byte, []int) {
	return file_proto_travelohi_v1_telemetry_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *GetRecentSearchesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetRecentSearchesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queries       []string               `protobuf:"bytes,1,rep,name=queries,proto3" json:"queries,omitempty"` // limit 3
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecentSearchesResponse) Reset() {
	*x = GetRecentSearchesResponse{}
	mi := &file_proto_travelohi_v1_telemetry_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecentSearchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentSearchesResponse) ProtoMessage() {}

func (x *GetRecentSearchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_travelohi_v1_telemetry_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentSearchesResponse.ProtoReflect.Descriptor instead.
func (*GetRecentSearchesResponse) Descriptor() ([]byte, []int) {
	return file_proto_travelohi_v1_telemetry_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *GetRecentSearchesResponse) GetQueries() []string {
	if x != nil {
		return x.Queries
	}
	return nil
}

type GetGlobalRecommendationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGlobalRecommendationsRequest) Reset() {
	*x = GetGlobalRecommendationsRequest{}
	mi := &file_proto_travelohi_v1_telemetry_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGlobalRecommendationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGlobalRecommendationsRequest) ProtoMessage() {}

func (x *GetGlobalRecommendationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_travelohi_v1_telemetry_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGlobalRecommendationsRequest.ProtoReflect.Descriptor instead.
func (*GetGlobalRecommendationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_travelohi_v1_telemetry_telemetry_proto_rawDescGZIP(), []int{3}
}

type GetGlobalRecommendationsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RecommendedQueries []string               `protobuf:"bytes,1,rep,name=recommended_queries,json=recommendedQueries,proto3" json:"recommended_queries,omitempty"` // limit 5
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetGlobalRecommendationsResponse) Reset() {
	*x = GetGlobalRecommendationsResponse{}
	mi := &file_proto_travelohi_v1_telemetry_telemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGlobalRecommendationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGlobalRecommendationsResponse) ProtoMessage() {}

func (x *GetGlobalRecommendationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_travelohi_v1_telemetry_telemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGlobalRecommendationsResponse.ProtoReflect.Descriptor instead.
func (*GetGlobalRecommendationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_travelohi_v1_telemetry_telemetry_proto_rawDescGZIP(), []int{4}
}

func (x *GetGlobalRecommendationsResponse) GetRecommendedQueries() []string {
	if x != nil {
		return x.RecommendedQueries
	}
	return nil
}

type GetPopularFlightsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPopularFlightsRequest) Reset() {
	*x = GetPopularFlightsRequest{}
	mi := &file_proto_travelohi_v1_telemetry_telemetry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPopularFlightsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPopularFlightsRequest) ProtoMessage() {}

func (x *GetPopularFlightsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_travelohi_v1_telemetry_telemetry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPopularFlightsRequest.ProtoReflect.Descriptor instead.
func (*GetPopularFlightsRequest) Descriptor() ([]byte, []int) {
	return file_proto_travelohi_v1_telemetry_telemetry_proto_rawDescGZIP(), []int{5}
}

type GetPopularFlightsResponse struct {
	state         protoimpl.MessageState                          `protogen:"open.v1"`
	Destinations  []*GetPopularFlightsResponse_PopularDestination `protobuf:"bytes,1,rep,name=destinations,proto3" json:"destinations,omitempty"` // limit 5
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPopularFlightsResponse) Reset() {
	*x = GetPopularFlightsResponse{}
	mi := &file_proto_travelohi_v1_telemetry_telemetry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPopularFlightsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPopularFlightsResponse) ProtoMessage() {}

func (x *GetPopularFlightsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_travelohi_v1_telemetry_telemetry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPopularFlightsResponse.ProtoReflect.Descriptor instead.
func (*GetPopularFlightsResponse) Descriptor() ([]byte, []int) {
	return file_proto_travelohi_v1_telemetry_telemetry_proto_rawDescGZIP(), []int{6}
}

func (x *GetPopularFlightsResponse) GetDestinations() []*GetPopularFlightsResponse_PopularDestination {
	if x != nil {
		return x.Destinations
	}
	return nil
}

type GetPopularHotelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPopularHotelsRequest) Reset() {
	*x = GetPopularHotelsRequest{}
	mi := &file_proto_travelohi_v1_telemetry_telemetry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPopularHotelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPopularHotelsRequest) ProtoMessage() {}

func (x *GetPopularHotelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_travelohi_v1_telemetry_telemetry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPopularHotelsRequest.ProtoReflect.Descriptor instead.
func (*GetPopularHotelsRequest) Descriptor() ([]byte, []int) {
	return file_proto_travelohi_v1_telemetry_telemetry_proto_rawDescGZIP(), []int{7}
}

type GetPopularHotelsResponse struct {
	state         protoimpl.MessageState                   `protogen:"open.v1"`
	Hotels        []*GetPopularHotelsResponse_PopularHotel `protobuf:"bytes,1,rep,name=hotels,proto3" json:"hotels,omitempty"` // limit 5
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPopularHotelsResponse) Reset() {
	*x = GetPopularHotelsResponse{}
	mi := &file_proto_travelohi_v1_telemetry_telemetry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPopularHotelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPopularHotelsResponse) ProtoMessage() {}

func (x *GetPopularHotelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_travelohi_v1_telemetry_telemetry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPopularHotelsResponse.ProtoReflect.Descriptor instead.
func (*GetPopularHotelsResponse) Descriptor() ([]byte, []int) {
	return file_proto_travelohi_v1_telemetry_telemetry_proto_rawDescGZIP(), []int{8}
}

func (x *GetPopularHotelsResponse) GetHotels() []*GetPopularHotelsResponse_PopularHotel {
	if x != nil {
		return x.Hotels
	}
	return nil
}

type TelemetryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryResponse) Reset() {
	*x = TelemetryResponse{}
	mi := &file_proto_travelohi_v1_telemetry_telemetry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryResponse) ProtoMessage() {}

func (x *TelemetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_travelohi_v1_telemetry_telemetry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryResponse.ProtoReflect.Descriptor instead.
func (*TelemetryResponse) Descriptor() ([]byte, []int) {
	return file_proto_travelohi_v1_telemetry_telemetry_proto_rawDescGZIP(), []int{9}
}

func (x *TelemetryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetPopularFlightsResponse_PopularDestination struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DestinationAirport string                 `protobuf:"bytes,1,opt,name=destination_airport,json=destinationAirport,proto3" json:"destination_airport,omitempty"`
	ImageUrl           string                 `protobuf:"bytes,2,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	BookingCount       int64                  `protobuf:"varint,3,opt,name=booking_count,json=bookingCount,proto3" json:"booking_count,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetPopularFlightsResponse_PopularDestination) Reset() {
	*x = GetPopularFlightsResponse_PopularDestination{}
	mi := &file_proto_travelohi_v1_telemetry_telemetry_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPopularFlightsResponse_PopularDestination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPopularFlightsResponse_PopularDestination) ProtoMessage() {}

func (x *GetPopularFlightsResponse_PopularDestination) ProtoReflect() protoreflect.Message {
	mi := &file_proto_travelohi_v1_telemetry_telemetry_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPopularFlightsResponse_PopularDestination.ProtoReflect.Descriptor instead.
func (*GetPopularFlightsResponse_PopularDestination) Descriptor() ([]byte, []int) {
	return file_proto_travelohi_v1_telemetry_telemetry_proto_rawDescGZIP(), []int{6, 0}
}

func (x *GetPopularFlightsResponse_PopularDestination) GetDestinationAirport() string {
	if x != nil {
		return x.DestinationAirport
	}
	return ""
}

func (x *GetPopularFlightsResponse_PopularDestination) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *GetPopularFlightsResponse_PopularDestination) GetBookingCount() int64 {
	if x != nil {
		return x.BookingCount
	}
	return 0
}

type GetPopularHotelsResponse_PopularHotel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HotelId       string                 `protobuf:"bytes,1,opt,name=hotel_id,json=hotelId,proto3" json:"hotel_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	BookingCount  int64                  `protobuf:"varint,5,opt,name=booking_count,json=bookingCount,proto3" json:"booking_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPopularHotelsResponse_PopularHotel) Reset() {
	*x = GetPopularHotelsResponse_PopularHotel{}
	mi := &file_proto_travelohi_v1_telemetry_telemetry_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPopularHotelsResponse_PopularHotel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPopularHotelsResponse_PopularHotel) ProtoMessage() {}

func (x *GetPopularHotelsResponse_PopularHotel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_travelohi_v1_telemetry_telemetry_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPopularHotelsResponse_PopularHotel.ProtoReflect.Descriptor instead.
func (*GetPopularHotelsResponse_PopularHotel) Descriptor() ([]byte, []int) {
	return file_proto_travelohi_v1_telemetry_telemetry_proto_rawDescGZIP(), []int{8, 0}
}

func (x *GetPopularHotelsResponse_PopularHotel) GetHotelId() string {
	if x != nil {
		return x.HotelId
	}
	return ""
}

func (x *GetPopularHotelsResponse_PopularHotel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetPopularHotelsResponse_PopularHotel) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *GetPopularHotelsResponse_PopularHotel) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *GetPopularHotelsResponse_PopularHotel) GetBookingCount() int64 {
	if x != nil {
		return x.BookingCount
	}
	return 0
}

var File_proto_travelohi_v1_telemetry_telemetry_proto protoreflect.FileDescriptor

const file_proto_travelohi_v1_telemetry_telemetry_proto_rawDesc = "" +
	"\n" +
	",proto/travelohi/v1/telemetry/telemetry.proto\x12\x16travelohi.v1.telemetry\"F\n" +
	"\x15LogSearchQueryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\"3\n" +
	"\x18GetRecentSearchesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"5\n" +
	"\x19GetRecentSearchesResponse\x12\x18\n" +
	"\aqueries\x18\x01 \x03(\tR\aqueries\"!\n" +
	"\x1fGetGlobalRecommendationsRequest\"S\n" +
	" GetGlobalRecommendationsResponse\x12/\n" +
	"\x13recommended_queries\x18\x01 \x03(\tR\x12recommendedQueries\"\x1a\n" +
	"\x18GetPopularFlightsRequest\"\x8f\x02\n" +
	"\x19GetPopularFlightsResponse\x12h\n" +
	"\fdestinations\x18\x01 \x03(\v2D.travelohi.v1.telemetry.GetPopularFlightsResponse.PopularDestinationR\fdestinations\x1a\x87\x01\n" +
	"\x12PopularDestination\x12/\n" +
	"\x13destination_airport\x18\x01 \x01(\tR\x12destinationAirport\x12\x1b\n" +
	"\timage_url\x18\x02 \x01(\tR\bimageUrl\x12#\n" +
	"\rbooking_count\x18\x03 \x01(\x03R\fbookingCount\"\x19\n" +
	"\x17GetPopularHotelsRequest\"\x8f\x02\n" +
	"\x18GetPopularHotelsResponse\x12U\n" +
	"\x06hotels\x18\x01 \x03(\v2=.travelohi.v1.telemetry.GetPopularHotelsResponse.PopularHotelR\x06hotels\x1a\x9b\x01\n" +
	"\fPopularHotel\x12\x19\n" +
	"\bhotel_id\x18\x01 \x01(\tR\ahotelId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12\x1b\n" +
	"\timage_url\x18\x04 \x01(\tR\bimageUrl\x12#\n" +
	"\rbooking_count\x18\x05 \x01(\x03R\fbookingCount\"-\n" +
	"\x11TelemetryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x8f\x05\n" +
	"\x10TelemetryService\x12l\n" +
	"\x0eLogSearchQuery\x12-.travelohi.v1.telemetry.LogSearchQueryRequest\x1a).travelohi.v1.telemetry.TelemetryResponse\"\x00\x12z\n" +
	"\x11GetRecentSearches\x120.travelohi.v1.telemetry.GetRecentSearchesRequest\x1a1.travelohi.v1.telemetry.GetRecentSearchesResponse\"\x00\x12\x8f\x01\n" +
	"\x18GetGlobalRecommendations\x127.travelohi.v1.telemetry.GetGlobalRecommendationsRequest\x1a8.travelohi.v1.telemetry.GetGlobalRecommendationsResponse\"\x00\x12\x85\x01\n" +
	"\x1cGetPopularFlightDestinations\x120.travelohi.v1.telemetry.GetPopularFlightsRequest\x1a1.travelohi.v1.telemetry.GetPopularFlightsResponse\"\x00\x12w\n" +
	"\x10GetPopularHotels\x12/.travelohi.v1.telemetry.GetPopularHotelsRequest\x1a0.travelohi.v1.telemetry.GetPopularHotelsResponse\"\x00B=Z;github.com/travelohi/backend/proto/telemetry/v1;telemetrypbb\x06proto3"

var (
	file_proto_travelohi_v1_telemetry_telemetry_proto_rawDescOnce sync.Once
	file_proto_travelohi_v1_telemetry_telemetry_proto_rawDescData []byte
)

func file_proto_travelohi_v1_telemetry_telemetry_proto_rawDescGZIP() []byte {
	file_proto_travelohi_v1_telemetry_telemetry_proto_rawDescOnce.Do(func() {
		file_proto_travelohi_v1_telemetry_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_travelohi_v1_telemetry_telemetry_proto_rawDesc), len(file_proto_travelohi_v1_telemetry_telemetry_proto_rawDesc)))
	})
	return file_proto_travelohi_v1_telemetry_telemetry_proto_rawDescData
}

var file_proto_travelohi_v1_telemetry_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_travelohi_v1_telemetry_telemetry_proto_goTypes = []any{
	(*LogSearchQueryRequest)(nil),                        // 0: travelohi.v1.telemetry.LogSearchQueryRequest
	(*GetRecentSearchesRequest)(nil),                     // 1: travelohi.v1.telemetry.GetRecentSearchesRequest
	(*GetRecentSearchesResponse)(nil),                    // 2: travelohi.v1.telemetry.GetRecentSearchesResponse
	(*GetGlobalRecommendationsRequest)(nil),              // 3: travelohi.v1.telemetry.GetGlobalRecommendationsRequest
	(*GetGlobalRecommendationsResponse)(nil),             // 4: travelohi.v1.telemetry.GetGlobalRecommendationsResponse
	(*GetPopularFlightsRequest)(nil),                     // 5: travelohi.v1.telemetry.GetPopularFlightsRequest
	(*GetPopularFlightsResponse)(nil),                    // 6: travelohi.v1.telemetry.GetPopularFlightsResponse
	(*GetPopularHotelsRequest)(nil),                      // 7: travelohi.v1.telemetry.GetPopularHotelsRequest
	(*GetPopularHotelsResponse)(nil),                     // 8: travelohi.v1.telemetry.GetPopularHotelsResponse
	(*TelemetryResponse)(nil),                            // 9: travelohi.v1.telemetry.TelemetryResponse
	(*GetPopularFlightsResponse_PopularDestination)(nil), // 10: travelohi.v1.telemetry.GetPopularFlightsResponse.PopularDestination
	(*GetPopularHotelsResponse_PopularHotel)(nil),        // 11: travelohi.v1.telemetry.GetPopularHotelsResponse.PopularHotel
}
var file_proto_travelohi_v1_telemetry_telemetry_proto_depIdxs = []int32{
	10, // 0: travelohi.v1.telemetry.GetPopularFlightsResponse.destinations:type_name -> travelohi.v1.telemetry.GetPopularFlightsResponse.PopularDestination
	11, // 1: travelohi.v1.telemetry.GetPopularHotelsResponse.hotels:type_name -> travelohi.v1.telemetry.GetPopularHotelsResponse.PopularHotel
	0,  // 2: travelohi.v1.telemetry.TelemetryService.LogSearchQuery:input_type -> travelohi.v1.telemetry.LogSearchQueryRequest
	1,  // 3: travelohi.v1.telemetry.TelemetryService.GetRecentSearches:input_type -> travelohi.v1.telemetry.GetRecentSearchesRequest
	3,  // 4: travelohi.v1.telemetry.TelemetryService.GetGlobalRecommendations:input_type -> travelohi.v1.telemetry.GetGlobalRecommendationsRequest
	5,  // 5: travelohi.v1.telemetry.TelemetryService.GetPopularFlightDestinations:input_type -> travelohi.v1.telemetry.GetPopularFlightsRequest
	7,  // 6: travelohi.v1.telemetry.TelemetryService.GetPopularHotels:input_type -> travelohi.v1.telemetry.GetPopularHotelsRequest
	9,  // 7: travelohi.v1.telemetry.TelemetryService.LogSearchQuery:output_type -> travelohi.v1.telemetry.TelemetryResponse
	2,  // 8: travelohi.v1.telemetry.TelemetryService.GetRecentSearches:output_type -> travelohi.v1.telemetry.GetRecentSearchesResponse
	4,  // 9: travelohi.v1.telemetry.TelemetryService.GetGlobalRecommendations:output_type -> travelohi.v1.telemetry.GetGlobalRecommendationsResponse
	6,  // 10: travelohi.v1.telemetry.TelemetryService.GetPopularFlightDestinations:output_type -> travelohi.v1.telemetry.GetPopularFlightsResponse
	8,  // 11: travelohi.v1.telemetry.TelemetryService.GetPopularHotels:output_type -> travelohi.v1.telemetry.GetPopularHotelsResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_travelohi_v1_telemetry_telemetry_proto_init() }
func file_proto_travelohi_v1_telemetry_telemetry_proto_init() {
	if File_proto_travelohi_v1_telemetry_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_travelohi_v1_telemetry_telemetry_proto_rawDesc), len(file_proto_travelohi_v1_telemetry_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_travelohi_v1_telemetry_telemetry_proto_goTypes,
		DependencyIndexes: file_proto_travelohi_v1_telemetry_telemetry_proto_depIdxs,
		MessageInfos:      file_proto_travelohi_v1_telemetry_telemetry_proto_msgTypes,
	}.Build()
	File_proto_travelohi_v1_telemetry_telemetry_proto = out.File
	file_proto_travelohi_v1_telemetry_telemetry_proto_goTypes = nil
	file_proto_travelohi_v1_telemetry_telemetry_proto_depIdxs = nil
}
