// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "travelohi/v1/account/account.proto" (package "travelohi.v1.account", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { AccountService } from "./account";
import type { GetExchangeRateResponse } from "./account";
import type { GetExchangeRateRequest } from "./account";
import type { RedeemWalletCouponRequest } from "./account";
import type { RefundWalletRequest } from "./account";
import type { WalletResponse } from "./account";
import type { DeductWalletRequest } from "./account";
import type { GetETicketResponse } from "./account";
import type { GetETicketRequest } from "./account";
import type { GetBookingHistoryResponse } from "./account";
import type { GetBookingHistoryRequest } from "./account";
import type { UpdateProfileResponse } from "./account";
import type { UpdateProfileRequest } from "./account";
import type { GetProfileResponse } from "./account";
import type { GetProfileRequest } from "./account";
import type { InternalCreateBookingResponse } from "./account";
import type { InternalCreateBookingRequest } from "./account";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { InitProfileResponse } from "./account";
import type { InitProfileRequest } from "./account";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service travelohi.v1.account.AccountService
 */
export interface IAccountServiceClient {
    /**
     * internal microservice  calls
     *
     * @generated from protobuf rpc: InitProfile
     */
    initProfile(input: InitProfileRequest, options?: RpcOptions): UnaryCall<InitProfileRequest, InitProfileResponse>;
    /**
     * @generated from protobuf rpc: InternalCreateBooking
     */
    internalCreateBooking(input: InternalCreateBookingRequest, options?: RpcOptions): UnaryCall<InternalCreateBookingRequest, InternalCreateBookingResponse>;
    /**
     * profile related
     *
     * @generated from protobuf rpc: GetProfile
     */
    getProfile(input: GetProfileRequest, options?: RpcOptions): UnaryCall<GetProfileRequest, GetProfileResponse>;
    /**
     * @generated from protobuf rpc: UpdateProfile
     */
    updateProfile(input: UpdateProfileRequest, options?: RpcOptions): UnaryCall<UpdateProfileRequest, UpdateProfileResponse>;
    /**
     * booking and history related
     *
     * @generated from protobuf rpc: GetBookingHistory
     */
    getBookingHistory(input: GetBookingHistoryRequest, options?: RpcOptions): UnaryCall<GetBookingHistoryRequest, GetBookingHistoryResponse>;
    /**
     * @generated from protobuf rpc: GetETicket
     */
    getETicket(input: GetETicketRequest, options?: RpcOptions): UnaryCall<GetETicketRequest, GetETicketResponse>;
    /**
     * payment and wallet related
     *
     * @generated from protobuf rpc: DeductWallet
     */
    deductWallet(input: DeductWalletRequest, options?: RpcOptions): UnaryCall<DeductWalletRequest, WalletResponse>;
    /**
     * @generated from protobuf rpc: RefundWallet
     */
    refundWallet(input: RefundWalletRequest, options?: RpcOptions): UnaryCall<RefundWalletRequest, WalletResponse>;
    /**
     * @generated from protobuf rpc: RedeemWalletCoupon
     */
    redeemWalletCoupon(input: RedeemWalletCouponRequest, options?: RpcOptions): UnaryCall<RedeemWalletCouponRequest, WalletResponse>;
    /**
     * @generated from protobuf rpc: GetExchangeRate
     */
    getExchangeRate(input: GetExchangeRateRequest, options?: RpcOptions): UnaryCall<GetExchangeRateRequest, GetExchangeRateResponse>;
}
/**
 * @generated from protobuf service travelohi.v1.account.AccountService
 */
export class AccountServiceClient implements IAccountServiceClient, ServiceInfo {
    typeName = AccountService.typeName;
    methods = AccountService.methods;
    options = AccountService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * internal microservice  calls
     *
     * @generated from protobuf rpc: InitProfile
     */
    initProfile(input: InitProfileRequest, options?: RpcOptions): UnaryCall<InitProfileRequest, InitProfileResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<InitProfileRequest, InitProfileResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: InternalCreateBooking
     */
    internalCreateBooking(input: InternalCreateBookingRequest, options?: RpcOptions): UnaryCall<InternalCreateBookingRequest, InternalCreateBookingResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<InternalCreateBookingRequest, InternalCreateBookingResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * profile related
     *
     * @generated from protobuf rpc: GetProfile
     */
    getProfile(input: GetProfileRequest, options?: RpcOptions): UnaryCall<GetProfileRequest, GetProfileResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetProfileRequest, GetProfileResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateProfile
     */
    updateProfile(input: UpdateProfileRequest, options?: RpcOptions): UnaryCall<UpdateProfileRequest, UpdateProfileResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateProfileRequest, UpdateProfileResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * booking and history related
     *
     * @generated from protobuf rpc: GetBookingHistory
     */
    getBookingHistory(input: GetBookingHistoryRequest, options?: RpcOptions): UnaryCall<GetBookingHistoryRequest, GetBookingHistoryResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetBookingHistoryRequest, GetBookingHistoryResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetETicket
     */
    getETicket(input: GetETicketRequest, options?: RpcOptions): UnaryCall<GetETicketRequest, GetETicketResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetETicketRequest, GetETicketResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * payment and wallet related
     *
     * @generated from protobuf rpc: DeductWallet
     */
    deductWallet(input: DeductWalletRequest, options?: RpcOptions): UnaryCall<DeductWalletRequest, WalletResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeductWalletRequest, WalletResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RefundWallet
     */
    refundWallet(input: RefundWalletRequest, options?: RpcOptions): UnaryCall<RefundWalletRequest, WalletResponse> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<RefundWalletRequest, WalletResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RedeemWalletCoupon
     */
    redeemWalletCoupon(input: RedeemWalletCouponRequest, options?: RpcOptions): UnaryCall<RedeemWalletCouponRequest, WalletResponse> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<RedeemWalletCouponRequest, WalletResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetExchangeRate
     */
    getExchangeRate(input: GetExchangeRateRequest, options?: RpcOptions): UnaryCall<GetExchangeRateRequest, GetExchangeRateResponse> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetExchangeRateRequest, GetExchangeRateResponse>("unary", this._transport, method, opt, input);
    }
}
