// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "travelohi/v1/cart/cart.proto" (package "travelohi.v1.cart", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message travelohi.v1.cart.CartItem
 */
export interface CartItem {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string item_type = 2
     */
    itemType: string;
    /**
     * @generated from protobuf field: string reference_id = 3
     */
    referenceId: string;
    /**
     * @generated from protobuf field: string display_name = 4
     */
    displayName: string;
    /**
     * @generated from protobuf field: string display_image_url = 5
     */
    displayImageUrl: string;
    /**
     * @generated from protobuf field: string check_in_date = 6
     */
    checkInDate: string;
    /**
     * @generated from protobuf field: string check_out_date = 7
     */
    checkOutDate: string;
    /**
     * @generated from protobuf field: int64 item_price = 8
     */
    itemPrice: bigint;
    /**
     * @generated from protobuf field: int32 quantity = 9
     */
    quantity: number;
    /**
     * @generated from protobuf field: string status = 10
     */
    status: string;
    /**
     * @generated from protobuf field: int32 luggage_weight = 11
     */
    luggageWeight: number;
}
/**
 * @generated from protobuf message travelohi.v1.cart.AddToCartRequest
 */
export interface AddToCartRequest {
    /**
     * @generated from protobuf field: string item_type = 1
     */
    itemType: string; // hotel or flight    /**
     * @generated from protobuf field: string reference_id = 2
     */
    referenceId: string;
    /**
     * @generated from protobuf field: string check_in_date = 3
     */
    checkInDate: string; // kalo pilih hotel     /**
     * @generated from protobuf field: string check_out_date = 4
     */
    checkOutDate: string; // kalo pilih hotel    /**
     * @generated from protobuf field: int32 quantity = 5
     */
    quantity: number;
    /**
     * @generated from protobuf field: int32 luggage_weight = 6
     */
    luggageWeight: number; // kalo pilih flight}
/**
 * @generated from protobuf message travelohi.v1.cart.ViewCartRequest
 */
export interface ViewCartRequest {
}
/**
 * @generated from protobuf message travelohi.v1.cart.ViewCartResponse
 */
export interface ViewCartResponse {
    /**
     * @generated from protobuf field: repeated travelohi.v1.cart.CartItem items = 1
     */
    items: CartItem[];
    /**
     * @generated from protobuf field: int64 subtotal = 2
     */
    subtotal: bigint;
    /**
     * @generated from protobuf field: int64 discount_amount = 3
     */
    discountAmount: bigint;
    /**
     * @generated from protobuf field: int64 total_price = 4
     */
    totalPrice: bigint;
    /**
     * @generated from protobuf field: string applied_promo_code = 5
     */
    appliedPromoCode: string;
}
/**
 * @generated from protobuf message travelohi.v1.cart.UpdateCartItemRequest
 */
export interface UpdateCartItemRequest {
    /**
     * @generated from protobuf field: string cart_item_id = 1
     */
    cartItemId: string;
    /**
     * @generated from protobuf field: string new_check_in_date = 2
     */
    newCheckInDate: string;
    /**
     * @generated from protobuf field: string new_check_out_date = 3
     */
    newCheckOutDate: string;
}
/**
 * @generated from protobuf message travelohi.v1.cart.RemoveFromCartRequest
 */
export interface RemoveFromCartRequest {
    /**
     * @generated from protobuf field: string cart_item_id = 1
     */
    cartItemId: string;
}
/**
 * @generated from protobuf message travelohi.v1.cart.ApplyPromoRequest
 */
export interface ApplyPromoRequest {
    /**
     * @generated from protobuf field: string promo_code = 1
     */
    promoCode: string;
}
/**
 * @generated from protobuf message travelohi.v1.cart.CheckoutRequest
 */
export interface CheckoutRequest {
    /**
     * @generated from protobuf field: string payment_method = 1
     */
    paymentMethod: string; // hi_wallet or credit_card    /**
     * @generated from protobuf field: string credit_card_id = 2
     */
    creditCardId: string;
    /**
     * @generated from protobuf field: string applied_promo_code = 3
     */
    appliedPromoCode: string;
}
/**
 * @generated from protobuf message travelohi.v1.cart.CheckoutResponse
 */
export interface CheckoutResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
    /**
     * @generated from protobuf field: string transaction_id = 3
     */
    transactionId: string;
}
/**
 * @generated from protobuf message travelohi.v1.cart.CartResponse
 */
export interface CartResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
}
/**
 * @generated from protobuf message travelohi.v1.cart.InternalCreatePromoRequest
 */
export interface InternalCreatePromoRequest {
    /**
     * @generated from protobuf field: string promo_code = 1
     */
    promoCode: string;
    /**
     * @generated from protobuf field: int64 discount_amount = 2
     */
    discountAmount: bigint;
    /**
     * @generated from protobuf field: int32 max_uses = 3
     */
    maxUses: number;
    /**
     * @generated from protobuf field: string expiry_date = 4
     */
    expiryDate: string;
}
/**
 * @generated from protobuf message travelohi.v1.cart.InternalCreatePromoResponse
 */
export interface InternalCreatePromoResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class CartItem$Type extends MessageType<CartItem> {
    constructor() {
        super("travelohi.v1.cart.CartItem", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "item_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "reference_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "display_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "display_image_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "check_in_date", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "check_out_date", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "item_price", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 9, name: "quantity", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 10, name: "status", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 11, name: "luggage_weight", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<CartItem>): CartItem {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.itemType = "";
        message.referenceId = "";
        message.displayName = "";
        message.displayImageUrl = "";
        message.checkInDate = "";
        message.checkOutDate = "";
        message.itemPrice = 0n;
        message.quantity = 0;
        message.status = "";
        message.luggageWeight = 0;
        if (value !== undefined)
            reflectionMergePartial<CartItem>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CartItem): CartItem {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string item_type */ 2:
                    message.itemType = reader.string();
                    break;
                case /* string reference_id */ 3:
                    message.referenceId = reader.string();
                    break;
                case /* string display_name */ 4:
                    message.displayName = reader.string();
                    break;
                case /* string display_image_url */ 5:
                    message.displayImageUrl = reader.string();
                    break;
                case /* string check_in_date */ 6:
                    message.checkInDate = reader.string();
                    break;
                case /* string check_out_date */ 7:
                    message.checkOutDate = reader.string();
                    break;
                case /* int64 item_price */ 8:
                    message.itemPrice = reader.int64().toBigInt();
                    break;
                case /* int32 quantity */ 9:
                    message.quantity = reader.int32();
                    break;
                case /* string status */ 10:
                    message.status = reader.string();
                    break;
                case /* int32 luggage_weight */ 11:
                    message.luggageWeight = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CartItem, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string item_type = 2; */
        if (message.itemType !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.itemType);
        /* string reference_id = 3; */
        if (message.referenceId !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.referenceId);
        /* string display_name = 4; */
        if (message.displayName !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.displayName);
        /* string display_image_url = 5; */
        if (message.displayImageUrl !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.displayImageUrl);
        /* string check_in_date = 6; */
        if (message.checkInDate !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.checkInDate);
        /* string check_out_date = 7; */
        if (message.checkOutDate !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.checkOutDate);
        /* int64 item_price = 8; */
        if (message.itemPrice !== 0n)
            writer.tag(8, WireType.Varint).int64(message.itemPrice);
        /* int32 quantity = 9; */
        if (message.quantity !== 0)
            writer.tag(9, WireType.Varint).int32(message.quantity);
        /* string status = 10; */
        if (message.status !== "")
            writer.tag(10, WireType.LengthDelimited).string(message.status);
        /* int32 luggage_weight = 11; */
        if (message.luggageWeight !== 0)
            writer.tag(11, WireType.Varint).int32(message.luggageWeight);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.cart.CartItem
 */
export const CartItem = new CartItem$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AddToCartRequest$Type extends MessageType<AddToCartRequest> {
    constructor() {
        super("travelohi.v1.cart.AddToCartRequest", [
            { no: 1, name: "item_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "reference_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "check_in_date", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "check_out_date", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "quantity", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "luggage_weight", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<AddToCartRequest>): AddToCartRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.itemType = "";
        message.referenceId = "";
        message.checkInDate = "";
        message.checkOutDate = "";
        message.quantity = 0;
        message.luggageWeight = 0;
        if (value !== undefined)
            reflectionMergePartial<AddToCartRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AddToCartRequest): AddToCartRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string item_type */ 1:
                    message.itemType = reader.string();
                    break;
                case /* string reference_id */ 2:
                    message.referenceId = reader.string();
                    break;
                case /* string check_in_date */ 3:
                    message.checkInDate = reader.string();
                    break;
                case /* string check_out_date */ 4:
                    message.checkOutDate = reader.string();
                    break;
                case /* int32 quantity */ 5:
                    message.quantity = reader.int32();
                    break;
                case /* int32 luggage_weight */ 6:
                    message.luggageWeight = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AddToCartRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string item_type = 1; */
        if (message.itemType !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.itemType);
        /* string reference_id = 2; */
        if (message.referenceId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.referenceId);
        /* string check_in_date = 3; */
        if (message.checkInDate !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.checkInDate);
        /* string check_out_date = 4; */
        if (message.checkOutDate !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.checkOutDate);
        /* int32 quantity = 5; */
        if (message.quantity !== 0)
            writer.tag(5, WireType.Varint).int32(message.quantity);
        /* int32 luggage_weight = 6; */
        if (message.luggageWeight !== 0)
            writer.tag(6, WireType.Varint).int32(message.luggageWeight);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.cart.AddToCartRequest
 */
export const AddToCartRequest = new AddToCartRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ViewCartRequest$Type extends MessageType<ViewCartRequest> {
    constructor() {
        super("travelohi.v1.cart.ViewCartRequest", []);
    }
    create(value?: PartialMessage<ViewCartRequest>): ViewCartRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<ViewCartRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ViewCartRequest): ViewCartRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ViewCartRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.cart.ViewCartRequest
 */
export const ViewCartRequest = new ViewCartRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ViewCartResponse$Type extends MessageType<ViewCartResponse> {
    constructor() {
        super("travelohi.v1.cart.ViewCartResponse", [
            { no: 1, name: "items", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => CartItem },
            { no: 2, name: "subtotal", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 3, name: "discount_amount", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 4, name: "total_price", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 5, name: "applied_promo_code", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ViewCartResponse>): ViewCartResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.items = [];
        message.subtotal = 0n;
        message.discountAmount = 0n;
        message.totalPrice = 0n;
        message.appliedPromoCode = "";
        if (value !== undefined)
            reflectionMergePartial<ViewCartResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ViewCartResponse): ViewCartResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated travelohi.v1.cart.CartItem items */ 1:
                    message.items.push(CartItem.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* int64 subtotal */ 2:
                    message.subtotal = reader.int64().toBigInt();
                    break;
                case /* int64 discount_amount */ 3:
                    message.discountAmount = reader.int64().toBigInt();
                    break;
                case /* int64 total_price */ 4:
                    message.totalPrice = reader.int64().toBigInt();
                    break;
                case /* string applied_promo_code */ 5:
                    message.appliedPromoCode = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ViewCartResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated travelohi.v1.cart.CartItem items = 1; */
        for (let i = 0; i < message.items.length; i++)
            CartItem.internalBinaryWrite(message.items[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* int64 subtotal = 2; */
        if (message.subtotal !== 0n)
            writer.tag(2, WireType.Varint).int64(message.subtotal);
        /* int64 discount_amount = 3; */
        if (message.discountAmount !== 0n)
            writer.tag(3, WireType.Varint).int64(message.discountAmount);
        /* int64 total_price = 4; */
        if (message.totalPrice !== 0n)
            writer.tag(4, WireType.Varint).int64(message.totalPrice);
        /* string applied_promo_code = 5; */
        if (message.appliedPromoCode !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.appliedPromoCode);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.cart.ViewCartResponse
 */
export const ViewCartResponse = new ViewCartResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateCartItemRequest$Type extends MessageType<UpdateCartItemRequest> {
    constructor() {
        super("travelohi.v1.cart.UpdateCartItemRequest", [
            { no: 1, name: "cart_item_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "new_check_in_date", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "new_check_out_date", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<UpdateCartItemRequest>): UpdateCartItemRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.cartItemId = "";
        message.newCheckInDate = "";
        message.newCheckOutDate = "";
        if (value !== undefined)
            reflectionMergePartial<UpdateCartItemRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateCartItemRequest): UpdateCartItemRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string cart_item_id */ 1:
                    message.cartItemId = reader.string();
                    break;
                case /* string new_check_in_date */ 2:
                    message.newCheckInDate = reader.string();
                    break;
                case /* string new_check_out_date */ 3:
                    message.newCheckOutDate = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateCartItemRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string cart_item_id = 1; */
        if (message.cartItemId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.cartItemId);
        /* string new_check_in_date = 2; */
        if (message.newCheckInDate !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.newCheckInDate);
        /* string new_check_out_date = 3; */
        if (message.newCheckOutDate !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.newCheckOutDate);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.cart.UpdateCartItemRequest
 */
export const UpdateCartItemRequest = new UpdateCartItemRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RemoveFromCartRequest$Type extends MessageType<RemoveFromCartRequest> {
    constructor() {
        super("travelohi.v1.cart.RemoveFromCartRequest", [
            { no: 1, name: "cart_item_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<RemoveFromCartRequest>): RemoveFromCartRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.cartItemId = "";
        if (value !== undefined)
            reflectionMergePartial<RemoveFromCartRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RemoveFromCartRequest): RemoveFromCartRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string cart_item_id */ 1:
                    message.cartItemId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RemoveFromCartRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string cart_item_id = 1; */
        if (message.cartItemId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.cartItemId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.cart.RemoveFromCartRequest
 */
export const RemoveFromCartRequest = new RemoveFromCartRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ApplyPromoRequest$Type extends MessageType<ApplyPromoRequest> {
    constructor() {
        super("travelohi.v1.cart.ApplyPromoRequest", [
            { no: 1, name: "promo_code", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ApplyPromoRequest>): ApplyPromoRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.promoCode = "";
        if (value !== undefined)
            reflectionMergePartial<ApplyPromoRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ApplyPromoRequest): ApplyPromoRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string promo_code */ 1:
                    message.promoCode = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ApplyPromoRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string promo_code = 1; */
        if (message.promoCode !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.promoCode);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.cart.ApplyPromoRequest
 */
export const ApplyPromoRequest = new ApplyPromoRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CheckoutRequest$Type extends MessageType<CheckoutRequest> {
    constructor() {
        super("travelohi.v1.cart.CheckoutRequest", [
            { no: 1, name: "payment_method", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "credit_card_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "applied_promo_code", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CheckoutRequest>): CheckoutRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.paymentMethod = "";
        message.creditCardId = "";
        message.appliedPromoCode = "";
        if (value !== undefined)
            reflectionMergePartial<CheckoutRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CheckoutRequest): CheckoutRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string payment_method */ 1:
                    message.paymentMethod = reader.string();
                    break;
                case /* string credit_card_id */ 2:
                    message.creditCardId = reader.string();
                    break;
                case /* string applied_promo_code */ 3:
                    message.appliedPromoCode = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CheckoutRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string payment_method = 1; */
        if (message.paymentMethod !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.paymentMethod);
        /* string credit_card_id = 2; */
        if (message.creditCardId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.creditCardId);
        /* string applied_promo_code = 3; */
        if (message.appliedPromoCode !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.appliedPromoCode);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.cart.CheckoutRequest
 */
export const CheckoutRequest = new CheckoutRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CheckoutResponse$Type extends MessageType<CheckoutResponse> {
    constructor() {
        super("travelohi.v1.cart.CheckoutResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "transaction_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CheckoutResponse>): CheckoutResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        message.message = "";
        message.transactionId = "";
        if (value !== undefined)
            reflectionMergePartial<CheckoutResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CheckoutResponse): CheckoutResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                case /* string transaction_id */ 3:
                    message.transactionId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CheckoutResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        /* string transaction_id = 3; */
        if (message.transactionId !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.transactionId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.cart.CheckoutResponse
 */
export const CheckoutResponse = new CheckoutResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CartResponse$Type extends MessageType<CartResponse> {
    constructor() {
        super("travelohi.v1.cart.CartResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CartResponse>): CartResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<CartResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CartResponse): CartResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CartResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.cart.CartResponse
 */
export const CartResponse = new CartResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class InternalCreatePromoRequest$Type extends MessageType<InternalCreatePromoRequest> {
    constructor() {
        super("travelohi.v1.cart.InternalCreatePromoRequest", [
            { no: 1, name: "promo_code", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "discount_amount", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 3, name: "max_uses", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "expiry_date", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<InternalCreatePromoRequest>): InternalCreatePromoRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.promoCode = "";
        message.discountAmount = 0n;
        message.maxUses = 0;
        message.expiryDate = "";
        if (value !== undefined)
            reflectionMergePartial<InternalCreatePromoRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: InternalCreatePromoRequest): InternalCreatePromoRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string promo_code */ 1:
                    message.promoCode = reader.string();
                    break;
                case /* int64 discount_amount */ 2:
                    message.discountAmount = reader.int64().toBigInt();
                    break;
                case /* int32 max_uses */ 3:
                    message.maxUses = reader.int32();
                    break;
                case /* string expiry_date */ 4:
                    message.expiryDate = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: InternalCreatePromoRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string promo_code = 1; */
        if (message.promoCode !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.promoCode);
        /* int64 discount_amount = 2; */
        if (message.discountAmount !== 0n)
            writer.tag(2, WireType.Varint).int64(message.discountAmount);
        /* int32 max_uses = 3; */
        if (message.maxUses !== 0)
            writer.tag(3, WireType.Varint).int32(message.maxUses);
        /* string expiry_date = 4; */
        if (message.expiryDate !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.expiryDate);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.cart.InternalCreatePromoRequest
 */
export const InternalCreatePromoRequest = new InternalCreatePromoRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class InternalCreatePromoResponse$Type extends MessageType<InternalCreatePromoResponse> {
    constructor() {
        super("travelohi.v1.cart.InternalCreatePromoResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<InternalCreatePromoResponse>): InternalCreatePromoResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<InternalCreatePromoResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: InternalCreatePromoResponse): InternalCreatePromoResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: InternalCreatePromoResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.cart.InternalCreatePromoResponse
 */
export const InternalCreatePromoResponse = new InternalCreatePromoResponse$Type();
/**
 * @generated ServiceType for protobuf service travelohi.v1.cart.CartService
 */
export const CartService = new ServiceType("travelohi.v1.cart.CartService", [
    { name: "AddToCart", options: {}, I: AddToCartRequest, O: CartResponse },
    { name: "ViewCart", options: {}, I: ViewCartRequest, O: ViewCartResponse },
    { name: "UpdateCartItem", options: {}, I: UpdateCartItemRequest, O: CartResponse },
    { name: "RemoveFromCart", options: {}, I: RemoveFromCartRequest, O: CartResponse },
    { name: "ApplyPromo", options: {}, I: ApplyPromoRequest, O: ViewCartResponse },
    { name: "Checkout", options: {}, I: CheckoutRequest, O: CheckoutResponse },
    { name: "InternalCreatePromo", options: {}, I: InternalCreatePromoRequest, O: InternalCreatePromoResponse }
]);
