// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "travelohi/v1/admin/admin.proto" (package "travelohi.v1.admin", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { AdminService } from "./admin";
import type { SendBroadcastRequest } from "./admin";
import type { BanUserRequest } from "./admin";
import type { GetAllUsersResponse } from "./admin";
import type { GetAllUsersRequest } from "./admin";
import type { GetAllPromosResponse } from "./admin";
import type { GetAllPromosRequest } from "./admin";
import type { TogglePromoRequest } from "./admin";
import type { CreatePromoRequest } from "./admin";
import type { InsertAirlineRequest } from "./admin";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { AdminResponse } from "./admin";
import type { InsertHotelRequest } from "./admin";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service travelohi.v1.admin.AdminService
 */
export interface IAdminServiceClient {
    /**
     * Inventory Ingestion
     *
     * @generated from protobuf rpc: InsertHotel
     */
    insertHotel(input: InsertHotelRequest, options?: RpcOptions): UnaryCall<InsertHotelRequest, AdminResponse>;
    /**
     * @generated from protobuf rpc: InsertAirline
     */
    insertAirline(input: InsertAirlineRequest, options?: RpcOptions): UnaryCall<InsertAirlineRequest, AdminResponse>;
    /**
     * Promo Management
     *
     * @generated from protobuf rpc: CreatePromo
     */
    createPromo(input: CreatePromoRequest, options?: RpcOptions): UnaryCall<CreatePromoRequest, AdminResponse>;
    /**
     * @generated from protobuf rpc: TogglePromoStatus
     */
    togglePromoStatus(input: TogglePromoRequest, options?: RpcOptions): UnaryCall<TogglePromoRequest, AdminResponse>;
    /**
     * @generated from protobuf rpc: GetAllPromos
     */
    getAllPromos(input: GetAllPromosRequest, options?: RpcOptions): UnaryCall<GetAllPromosRequest, GetAllPromosResponse>;
    /**
     * User Management
     *
     * @generated from protobuf rpc: GetAllUsers
     */
    getAllUsers(input: GetAllUsersRequest, options?: RpcOptions): UnaryCall<GetAllUsersRequest, GetAllUsersResponse>;
    /**
     * @generated from protobuf rpc: BanUser
     */
    banUser(input: BanUserRequest, options?: RpcOptions): UnaryCall<BanUserRequest, AdminResponse>;
    /**
     * Notification
     *
     * @generated from protobuf rpc: SendBroadcast
     */
    sendBroadcast(input: SendBroadcastRequest, options?: RpcOptions): UnaryCall<SendBroadcastRequest, AdminResponse>;
}
/**
 * @generated from protobuf service travelohi.v1.admin.AdminService
 */
export class AdminServiceClient implements IAdminServiceClient, ServiceInfo {
    typeName = AdminService.typeName;
    methods = AdminService.methods;
    options = AdminService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Inventory Ingestion
     *
     * @generated from protobuf rpc: InsertHotel
     */
    insertHotel(input: InsertHotelRequest, options?: RpcOptions): UnaryCall<InsertHotelRequest, AdminResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<InsertHotelRequest, AdminResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: InsertAirline
     */
    insertAirline(input: InsertAirlineRequest, options?: RpcOptions): UnaryCall<InsertAirlineRequest, AdminResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<InsertAirlineRequest, AdminResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Promo Management
     *
     * @generated from protobuf rpc: CreatePromo
     */
    createPromo(input: CreatePromoRequest, options?: RpcOptions): UnaryCall<CreatePromoRequest, AdminResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreatePromoRequest, AdminResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: TogglePromoStatus
     */
    togglePromoStatus(input: TogglePromoRequest, options?: RpcOptions): UnaryCall<TogglePromoRequest, AdminResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<TogglePromoRequest, AdminResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetAllPromos
     */
    getAllPromos(input: GetAllPromosRequest, options?: RpcOptions): UnaryCall<GetAllPromosRequest, GetAllPromosResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAllPromosRequest, GetAllPromosResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * User Management
     *
     * @generated from protobuf rpc: GetAllUsers
     */
    getAllUsers(input: GetAllUsersRequest, options?: RpcOptions): UnaryCall<GetAllUsersRequest, GetAllUsersResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAllUsersRequest, GetAllUsersResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: BanUser
     */
    banUser(input: BanUserRequest, options?: RpcOptions): UnaryCall<BanUserRequest, AdminResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<BanUserRequest, AdminResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Notification
     *
     * @generated from protobuf rpc: SendBroadcast
     */
    sendBroadcast(input: SendBroadcastRequest, options?: RpcOptions): UnaryCall<SendBroadcastRequest, AdminResponse> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<SendBroadcastRequest, AdminResponse>("unary", this._transport, method, opt, input);
    }
}
