// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "travelohi/v1/telemetry/telemetry.proto" (package "travelohi.v1.telemetry", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message travelohi.v1.telemetry.GlobalSearchRequest
 */
export interface GlobalSearchRequest {
    /**
     * @generated from protobuf field: string query = 1
     */
    query: string;
}
/**
 * @generated from protobuf message travelohi.v1.telemetry.HotelSearchResult
 */
export interface HotelSearchResult {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string name = 2
     */
    name: string;
    /**
     * @generated from protobuf field: string location = 3
     */
    location: string;
    /**
     * @generated from protobuf field: string image_url = 4
     */
    imageUrl: string;
}
/**
 * @generated from protobuf message travelohi.v1.telemetry.AirlineSearchResult
 */
export interface AirlineSearchResult {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string name = 2
     */
    name: string;
    /**
     * @generated from protobuf field: string logo_url = 3
     */
    logoUrl: string;
}
/**
 * @generated from protobuf message travelohi.v1.telemetry.GlobalSearchResponse
 */
export interface GlobalSearchResponse {
    /**
     * @generated from protobuf field: repeated travelohi.v1.telemetry.HotelSearchResult hotels = 1
     */
    hotels: HotelSearchResult[];
    /**
     * @generated from protobuf field: repeated travelohi.v1.telemetry.AirlineSearchResult airlines = 2
     */
    airlines: AirlineSearchResult[];
}
/**
 * @generated from protobuf message travelohi.v1.telemetry.LogSearchQueryRequest
 */
export interface LogSearchQueryRequest {
    /**
     * @generated from protobuf field: string user_id = 1
     */
    userId: string;
    /**
     * @generated from protobuf field: string query = 2
     */
    query: string;
}
/**
 * @generated from protobuf message travelohi.v1.telemetry.GetRecentSearchesRequest
 */
export interface GetRecentSearchesRequest {
    /**
     * @generated from protobuf field: string user_id = 1
     */
    userId: string;
}
/**
 * @generated from protobuf message travelohi.v1.telemetry.GetRecentSearchesResponse
 */
export interface GetRecentSearchesResponse {
    /**
     * @generated from protobuf field: repeated string queries = 1
     */
    queries: string[]; // limit 3
}
/**
 * @generated from protobuf message travelohi.v1.telemetry.GetGlobalRecommendationsRequest
 */
export interface GetGlobalRecommendationsRequest {
}
/**
 * @generated from protobuf message travelohi.v1.telemetry.GetGlobalRecommendationsResponse
 */
export interface GetGlobalRecommendationsResponse {
    /**
     * @generated from protobuf field: repeated string recommended_queries = 1
     */
    recommendedQueries: string[]; // limit 5
}
/**
 * @generated from protobuf message travelohi.v1.telemetry.GetPopularFlightsRequest
 */
export interface GetPopularFlightsRequest {
}
/**
 * @generated from protobuf message travelohi.v1.telemetry.GetPopularFlightsResponse
 */
export interface GetPopularFlightsResponse {
    /**
     * @generated from protobuf field: repeated travelohi.v1.telemetry.GetPopularFlightsResponse.PopularDestination destinations = 1
     */
    destinations: GetPopularFlightsResponse_PopularDestination[]; // limit 5
}
/**
 * @generated from protobuf message travelohi.v1.telemetry.GetPopularFlightsResponse.PopularDestination
 */
export interface GetPopularFlightsResponse_PopularDestination {
    /**
     * @generated from protobuf field: string destination_airport = 1
     */
    destinationAirport: string;
    /**
     * @generated from protobuf field: string image_url = 2
     */
    imageUrl: string;
    /**
     * @generated from protobuf field: int64 booking_count = 3
     */
    bookingCount: bigint;
}
/**
 * @generated from protobuf message travelohi.v1.telemetry.GetPopularHotelsRequest
 */
export interface GetPopularHotelsRequest {
}
/**
 * @generated from protobuf message travelohi.v1.telemetry.GetPopularHotelsResponse
 */
export interface GetPopularHotelsResponse {
    /**
     * @generated from protobuf field: repeated travelohi.v1.telemetry.GetPopularHotelsResponse.PopularHotel hotels = 1
     */
    hotels: GetPopularHotelsResponse_PopularHotel[]; // limit 5
}
/**
 * @generated from protobuf message travelohi.v1.telemetry.GetPopularHotelsResponse.PopularHotel
 */
export interface GetPopularHotelsResponse_PopularHotel {
    /**
     * @generated from protobuf field: string hotel_id = 1
     */
    hotelId: string;
    /**
     * @generated from protobuf field: string name = 2
     */
    name: string;
    /**
     * @generated from protobuf field: string location = 3
     */
    location: string;
    /**
     * @generated from protobuf field: string image_url = 4
     */
    imageUrl: string;
    /**
     * @generated from protobuf field: int64 booking_count = 5
     */
    bookingCount: bigint;
}
/**
 * @generated from protobuf message travelohi.v1.telemetry.TelemetryResponse
 */
export interface TelemetryResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
}
// @generated message type with reflection information, may provide speed optimized methods
class GlobalSearchRequest$Type extends MessageType<GlobalSearchRequest> {
    constructor() {
        super("travelohi.v1.telemetry.GlobalSearchRequest", [
            { no: 1, name: "query", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GlobalSearchRequest>): GlobalSearchRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.query = "";
        if (value !== undefined)
            reflectionMergePartial<GlobalSearchRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GlobalSearchRequest): GlobalSearchRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string query */ 1:
                    message.query = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GlobalSearchRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string query = 1; */
        if (message.query !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.query);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.telemetry.GlobalSearchRequest
 */
export const GlobalSearchRequest = new GlobalSearchRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class HotelSearchResult$Type extends MessageType<HotelSearchResult> {
    constructor() {
        super("travelohi.v1.telemetry.HotelSearchResult", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "location", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "image_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<HotelSearchResult>): HotelSearchResult {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.name = "";
        message.location = "";
        message.imageUrl = "";
        if (value !== undefined)
            reflectionMergePartial<HotelSearchResult>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: HotelSearchResult): HotelSearchResult {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* string location */ 3:
                    message.location = reader.string();
                    break;
                case /* string image_url */ 4:
                    message.imageUrl = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: HotelSearchResult, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* string location = 3; */
        if (message.location !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.location);
        /* string image_url = 4; */
        if (message.imageUrl !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.imageUrl);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.telemetry.HotelSearchResult
 */
export const HotelSearchResult = new HotelSearchResult$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AirlineSearchResult$Type extends MessageType<AirlineSearchResult> {
    constructor() {
        super("travelohi.v1.telemetry.AirlineSearchResult", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "logo_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<AirlineSearchResult>): AirlineSearchResult {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.name = "";
        message.logoUrl = "";
        if (value !== undefined)
            reflectionMergePartial<AirlineSearchResult>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AirlineSearchResult): AirlineSearchResult {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* string logo_url */ 3:
                    message.logoUrl = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AirlineSearchResult, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* string logo_url = 3; */
        if (message.logoUrl !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.logoUrl);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.telemetry.AirlineSearchResult
 */
export const AirlineSearchResult = new AirlineSearchResult$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GlobalSearchResponse$Type extends MessageType<GlobalSearchResponse> {
    constructor() {
        super("travelohi.v1.telemetry.GlobalSearchResponse", [
            { no: 1, name: "hotels", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => HotelSearchResult },
            { no: 2, name: "airlines", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => AirlineSearchResult }
        ]);
    }
    create(value?: PartialMessage<GlobalSearchResponse>): GlobalSearchResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.hotels = [];
        message.airlines = [];
        if (value !== undefined)
            reflectionMergePartial<GlobalSearchResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GlobalSearchResponse): GlobalSearchResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated travelohi.v1.telemetry.HotelSearchResult hotels */ 1:
                    message.hotels.push(HotelSearchResult.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated travelohi.v1.telemetry.AirlineSearchResult airlines */ 2:
                    message.airlines.push(AirlineSearchResult.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GlobalSearchResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated travelohi.v1.telemetry.HotelSearchResult hotels = 1; */
        for (let i = 0; i < message.hotels.length; i++)
            HotelSearchResult.internalBinaryWrite(message.hotels[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* repeated travelohi.v1.telemetry.AirlineSearchResult airlines = 2; */
        for (let i = 0; i < message.airlines.length; i++)
            AirlineSearchResult.internalBinaryWrite(message.airlines[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.telemetry.GlobalSearchResponse
 */
export const GlobalSearchResponse = new GlobalSearchResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LogSearchQueryRequest$Type extends MessageType<LogSearchQueryRequest> {
    constructor() {
        super("travelohi.v1.telemetry.LogSearchQueryRequest", [
            { no: 1, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "query", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<LogSearchQueryRequest>): LogSearchQueryRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.userId = "";
        message.query = "";
        if (value !== undefined)
            reflectionMergePartial<LogSearchQueryRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LogSearchQueryRequest): LogSearchQueryRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string user_id */ 1:
                    message.userId = reader.string();
                    break;
                case /* string query */ 2:
                    message.query = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LogSearchQueryRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string user_id = 1; */
        if (message.userId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.userId);
        /* string query = 2; */
        if (message.query !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.query);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.telemetry.LogSearchQueryRequest
 */
export const LogSearchQueryRequest = new LogSearchQueryRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetRecentSearchesRequest$Type extends MessageType<GetRecentSearchesRequest> {
    constructor() {
        super("travelohi.v1.telemetry.GetRecentSearchesRequest", [
            { no: 1, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetRecentSearchesRequest>): GetRecentSearchesRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.userId = "";
        if (value !== undefined)
            reflectionMergePartial<GetRecentSearchesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetRecentSearchesRequest): GetRecentSearchesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string user_id */ 1:
                    message.userId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetRecentSearchesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string user_id = 1; */
        if (message.userId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.userId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.telemetry.GetRecentSearchesRequest
 */
export const GetRecentSearchesRequest = new GetRecentSearchesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetRecentSearchesResponse$Type extends MessageType<GetRecentSearchesResponse> {
    constructor() {
        super("travelohi.v1.telemetry.GetRecentSearchesResponse", [
            { no: 1, name: "queries", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetRecentSearchesResponse>): GetRecentSearchesResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.queries = [];
        if (value !== undefined)
            reflectionMergePartial<GetRecentSearchesResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetRecentSearchesResponse): GetRecentSearchesResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated string queries */ 1:
                    message.queries.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetRecentSearchesResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated string queries = 1; */
        for (let i = 0; i < message.queries.length; i++)
            writer.tag(1, WireType.LengthDelimited).string(message.queries[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.telemetry.GetRecentSearchesResponse
 */
export const GetRecentSearchesResponse = new GetRecentSearchesResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetGlobalRecommendationsRequest$Type extends MessageType<GetGlobalRecommendationsRequest> {
    constructor() {
        super("travelohi.v1.telemetry.GetGlobalRecommendationsRequest", []);
    }
    create(value?: PartialMessage<GetGlobalRecommendationsRequest>): GetGlobalRecommendationsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetGlobalRecommendationsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetGlobalRecommendationsRequest): GetGlobalRecommendationsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetGlobalRecommendationsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.telemetry.GetGlobalRecommendationsRequest
 */
export const GetGlobalRecommendationsRequest = new GetGlobalRecommendationsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetGlobalRecommendationsResponse$Type extends MessageType<GetGlobalRecommendationsResponse> {
    constructor() {
        super("travelohi.v1.telemetry.GetGlobalRecommendationsResponse", [
            { no: 1, name: "recommended_queries", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetGlobalRecommendationsResponse>): GetGlobalRecommendationsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.recommendedQueries = [];
        if (value !== undefined)
            reflectionMergePartial<GetGlobalRecommendationsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetGlobalRecommendationsResponse): GetGlobalRecommendationsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated string recommended_queries */ 1:
                    message.recommendedQueries.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetGlobalRecommendationsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated string recommended_queries = 1; */
        for (let i = 0; i < message.recommendedQueries.length; i++)
            writer.tag(1, WireType.LengthDelimited).string(message.recommendedQueries[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.telemetry.GetGlobalRecommendationsResponse
 */
export const GetGlobalRecommendationsResponse = new GetGlobalRecommendationsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetPopularFlightsRequest$Type extends MessageType<GetPopularFlightsRequest> {
    constructor() {
        super("travelohi.v1.telemetry.GetPopularFlightsRequest", []);
    }
    create(value?: PartialMessage<GetPopularFlightsRequest>): GetPopularFlightsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetPopularFlightsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetPopularFlightsRequest): GetPopularFlightsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetPopularFlightsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.telemetry.GetPopularFlightsRequest
 */
export const GetPopularFlightsRequest = new GetPopularFlightsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetPopularFlightsResponse$Type extends MessageType<GetPopularFlightsResponse> {
    constructor() {
        super("travelohi.v1.telemetry.GetPopularFlightsResponse", [
            { no: 1, name: "destinations", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => GetPopularFlightsResponse_PopularDestination }
        ]);
    }
    create(value?: PartialMessage<GetPopularFlightsResponse>): GetPopularFlightsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.destinations = [];
        if (value !== undefined)
            reflectionMergePartial<GetPopularFlightsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetPopularFlightsResponse): GetPopularFlightsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated travelohi.v1.telemetry.GetPopularFlightsResponse.PopularDestination destinations */ 1:
                    message.destinations.push(GetPopularFlightsResponse_PopularDestination.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetPopularFlightsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated travelohi.v1.telemetry.GetPopularFlightsResponse.PopularDestination destinations = 1; */
        for (let i = 0; i < message.destinations.length; i++)
            GetPopularFlightsResponse_PopularDestination.internalBinaryWrite(message.destinations[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.telemetry.GetPopularFlightsResponse
 */
export const GetPopularFlightsResponse = new GetPopularFlightsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetPopularFlightsResponse_PopularDestination$Type extends MessageType<GetPopularFlightsResponse_PopularDestination> {
    constructor() {
        super("travelohi.v1.telemetry.GetPopularFlightsResponse.PopularDestination", [
            { no: 1, name: "destination_airport", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "image_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "booking_count", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<GetPopularFlightsResponse_PopularDestination>): GetPopularFlightsResponse_PopularDestination {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.destinationAirport = "";
        message.imageUrl = "";
        message.bookingCount = 0n;
        if (value !== undefined)
            reflectionMergePartial<GetPopularFlightsResponse_PopularDestination>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetPopularFlightsResponse_PopularDestination): GetPopularFlightsResponse_PopularDestination {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string destination_airport */ 1:
                    message.destinationAirport = reader.string();
                    break;
                case /* string image_url */ 2:
                    message.imageUrl = reader.string();
                    break;
                case /* int64 booking_count */ 3:
                    message.bookingCount = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetPopularFlightsResponse_PopularDestination, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string destination_airport = 1; */
        if (message.destinationAirport !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.destinationAirport);
        /* string image_url = 2; */
        if (message.imageUrl !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.imageUrl);
        /* int64 booking_count = 3; */
        if (message.bookingCount !== 0n)
            writer.tag(3, WireType.Varint).int64(message.bookingCount);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.telemetry.GetPopularFlightsResponse.PopularDestination
 */
export const GetPopularFlightsResponse_PopularDestination = new GetPopularFlightsResponse_PopularDestination$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetPopularHotelsRequest$Type extends MessageType<GetPopularHotelsRequest> {
    constructor() {
        super("travelohi.v1.telemetry.GetPopularHotelsRequest", []);
    }
    create(value?: PartialMessage<GetPopularHotelsRequest>): GetPopularHotelsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetPopularHotelsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetPopularHotelsRequest): GetPopularHotelsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetPopularHotelsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.telemetry.GetPopularHotelsRequest
 */
export const GetPopularHotelsRequest = new GetPopularHotelsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetPopularHotelsResponse$Type extends MessageType<GetPopularHotelsResponse> {
    constructor() {
        super("travelohi.v1.telemetry.GetPopularHotelsResponse", [
            { no: 1, name: "hotels", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => GetPopularHotelsResponse_PopularHotel }
        ]);
    }
    create(value?: PartialMessage<GetPopularHotelsResponse>): GetPopularHotelsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.hotels = [];
        if (value !== undefined)
            reflectionMergePartial<GetPopularHotelsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetPopularHotelsResponse): GetPopularHotelsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated travelohi.v1.telemetry.GetPopularHotelsResponse.PopularHotel hotels */ 1:
                    message.hotels.push(GetPopularHotelsResponse_PopularHotel.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetPopularHotelsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated travelohi.v1.telemetry.GetPopularHotelsResponse.PopularHotel hotels = 1; */
        for (let i = 0; i < message.hotels.length; i++)
            GetPopularHotelsResponse_PopularHotel.internalBinaryWrite(message.hotels[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.telemetry.GetPopularHotelsResponse
 */
export const GetPopularHotelsResponse = new GetPopularHotelsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetPopularHotelsResponse_PopularHotel$Type extends MessageType<GetPopularHotelsResponse_PopularHotel> {
    constructor() {
        super("travelohi.v1.telemetry.GetPopularHotelsResponse.PopularHotel", [
            { no: 1, name: "hotel_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "location", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "image_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "booking_count", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<GetPopularHotelsResponse_PopularHotel>): GetPopularHotelsResponse_PopularHotel {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.hotelId = "";
        message.name = "";
        message.location = "";
        message.imageUrl = "";
        message.bookingCount = 0n;
        if (value !== undefined)
            reflectionMergePartial<GetPopularHotelsResponse_PopularHotel>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetPopularHotelsResponse_PopularHotel): GetPopularHotelsResponse_PopularHotel {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string hotel_id */ 1:
                    message.hotelId = reader.string();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* string location */ 3:
                    message.location = reader.string();
                    break;
                case /* string image_url */ 4:
                    message.imageUrl = reader.string();
                    break;
                case /* int64 booking_count */ 5:
                    message.bookingCount = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetPopularHotelsResponse_PopularHotel, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string hotel_id = 1; */
        if (message.hotelId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.hotelId);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* string location = 3; */
        if (message.location !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.location);
        /* string image_url = 4; */
        if (message.imageUrl !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.imageUrl);
        /* int64 booking_count = 5; */
        if (message.bookingCount !== 0n)
            writer.tag(5, WireType.Varint).int64(message.bookingCount);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.telemetry.GetPopularHotelsResponse.PopularHotel
 */
export const GetPopularHotelsResponse_PopularHotel = new GetPopularHotelsResponse_PopularHotel$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TelemetryResponse$Type extends MessageType<TelemetryResponse> {
    constructor() {
        super("travelohi.v1.telemetry.TelemetryResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<TelemetryResponse>): TelemetryResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        if (value !== undefined)
            reflectionMergePartial<TelemetryResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TelemetryResponse): TelemetryResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TelemetryResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.telemetry.TelemetryResponse
 */
export const TelemetryResponse = new TelemetryResponse$Type();
/**
 * @generated ServiceType for protobuf service travelohi.v1.telemetry.TelemetryService
 */
export const TelemetryService = new ServiceType("travelohi.v1.telemetry.TelemetryService", [
    { name: "LogSearchQuery", options: {}, I: LogSearchQueryRequest, O: TelemetryResponse },
    { name: "GetRecentSearches", options: {}, I: GetRecentSearchesRequest, O: GetRecentSearchesResponse },
    { name: "GetGlobalRecommendations", options: {}, I: GetGlobalRecommendationsRequest, O: GetGlobalRecommendationsResponse },
    { name: "GetPopularFlightDestinations", options: {}, I: GetPopularFlightsRequest, O: GetPopularFlightsResponse },
    { name: "GetPopularHotels", options: {}, I: GetPopularHotelsRequest, O: GetPopularHotelsResponse },
    { name: "GlobalSearch", options: {}, I: GlobalSearchRequest, O: GlobalSearchResponse }
]);
