// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/travelohi/v1/flight/flight.proto

package flightpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FlightService_SearchFlights_FullMethodName      = "/travelohi.v1.flight.FlightService/SearchFlights"
	FlightService_GetFlightDetails_FullMethodName   = "/travelohi.v1.flight.FlightService/GetFlightDetails"
	FlightService_InternalLockSeat_FullMethodName   = "/travelohi.v1.flight.FlightService/InternalLockSeat"
	FlightService_InternalUnlockSeat_FullMethodName = "/travelohi.v1.flight.FlightService/InternalUnlockSeat"
	FlightService_GetFlightSeats_FullMethodName     = "/travelohi.v1.flight.FlightService/GetFlightSeats"
)

// FlightServiceClient is the client API for FlightService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FlightServiceClient interface {
	SearchFlights(ctx context.Context, in *SearchFlightsRequest, opts ...grpc.CallOption) (*SearchFlightsResponse, error)
	GetFlightDetails(ctx context.Context, in *GetFlightDetailsRequest, opts ...grpc.CallOption) (*GetFlightDetailsResponse, error)
	InternalLockSeat(ctx context.Context, in *LockSeatRequest, opts ...grpc.CallOption) (*LockSeatResponse, error)
	InternalUnlockSeat(ctx context.Context, in *UnlockSeatRequest, opts ...grpc.CallOption) (*UnlockSeatResponse, error)
	GetFlightSeats(ctx context.Context, in *GetFlightSeatsRequest, opts ...grpc.CallOption) (*GetFlightSeatsResponse, error)
}

type flightServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFlightServiceClient(cc grpc.ClientConnInterface) FlightServiceClient {
	return &flightServiceClient{cc}
}

func (c *flightServiceClient) SearchFlights(ctx context.Context, in *SearchFlightsRequest, opts ...grpc.CallOption) (*SearchFlightsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchFlightsResponse)
	err := c.cc.Invoke(ctx, FlightService_SearchFlights_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flightServiceClient) GetFlightDetails(ctx context.Context, in *GetFlightDetailsRequest, opts ...grpc.CallOption) (*GetFlightDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFlightDetailsResponse)
	err := c.cc.Invoke(ctx, FlightService_GetFlightDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flightServiceClient) InternalLockSeat(ctx context.Context, in *LockSeatRequest, opts ...grpc.CallOption) (*LockSeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LockSeatResponse)
	err := c.cc.Invoke(ctx, FlightService_InternalLockSeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flightServiceClient) InternalUnlockSeat(ctx context.Context, in *UnlockSeatRequest, opts ...grpc.CallOption) (*UnlockSeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnlockSeatResponse)
	err := c.cc.Invoke(ctx, FlightService_InternalUnlockSeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flightServiceClient) GetFlightSeats(ctx context.Context, in *GetFlightSeatsRequest, opts ...grpc.CallOption) (*GetFlightSeatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFlightSeatsResponse)
	err := c.cc.Invoke(ctx, FlightService_GetFlightSeats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlightServiceServer is the server API for FlightService service.
// All implementations must embed UnimplementedFlightServiceServer
// for forward compatibility.
type FlightServiceServer interface {
	SearchFlights(context.Context, *SearchFlightsRequest) (*SearchFlightsResponse, error)
	GetFlightDetails(context.Context, *GetFlightDetailsRequest) (*GetFlightDetailsResponse, error)
	InternalLockSeat(context.Context, *LockSeatRequest) (*LockSeatResponse, error)
	InternalUnlockSeat(context.Context, *UnlockSeatRequest) (*UnlockSeatResponse, error)
	GetFlightSeats(context.Context, *GetFlightSeatsRequest) (*GetFlightSeatsResponse, error)
	mustEmbedUnimplementedFlightServiceServer()
}

// UnimplementedFlightServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFlightServiceServer struct{}

func (UnimplementedFlightServiceServer) SearchFlights(context.Context, *SearchFlightsRequest) (*SearchFlightsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchFlights not implemented")
}
func (UnimplementedFlightServiceServer) GetFlightDetails(context.Context, *GetFlightDetailsRequest) (*GetFlightDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFlightDetails not implemented")
}
func (UnimplementedFlightServiceServer) InternalLockSeat(context.Context, *LockSeatRequest) (*LockSeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InternalLockSeat not implemented")
}
func (UnimplementedFlightServiceServer) InternalUnlockSeat(context.Context, *UnlockSeatRequest) (*UnlockSeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InternalUnlockSeat not implemented")
}
func (UnimplementedFlightServiceServer) GetFlightSeats(context.Context, *GetFlightSeatsRequest) (*GetFlightSeatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFlightSeats not implemented")
}
func (UnimplementedFlightServiceServer) mustEmbedUnimplementedFlightServiceServer() {}
func (UnimplementedFlightServiceServer) testEmbeddedByValue()                       {}

// UnsafeFlightServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlightServiceServer will
// result in compilation errors.
type UnsafeFlightServiceServer interface {
	mustEmbedUnimplementedFlightServiceServer()
}

func RegisterFlightServiceServer(s grpc.ServiceRegistrar, srv FlightServiceServer) {
	// If the following call panics, it indicates UnimplementedFlightServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FlightService_ServiceDesc, srv)
}

func _FlightService_SearchFlights_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchFlightsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightServiceServer).SearchFlights(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlightService_SearchFlights_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightServiceServer).SearchFlights(ctx, req.(*SearchFlightsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlightService_GetFlightDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFlightDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightServiceServer).GetFlightDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlightService_GetFlightDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightServiceServer).GetFlightDetails(ctx, req.(*GetFlightDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlightService_InternalLockSeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockSeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightServiceServer).InternalLockSeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlightService_InternalLockSeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightServiceServer).InternalLockSeat(ctx, req.(*LockSeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlightService_InternalUnlockSeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockSeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightServiceServer).InternalUnlockSeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlightService_InternalUnlockSeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightServiceServer).InternalUnlockSeat(ctx, req.(*UnlockSeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlightService_GetFlightSeats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFlightSeatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightServiceServer).GetFlightSeats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlightService_GetFlightSeats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightServiceServer).GetFlightSeats(ctx, req.(*GetFlightSeatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FlightService_ServiceDesc is the grpc.ServiceDesc for FlightService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FlightService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "travelohi.v1.flight.FlightService",
	HandlerType: (*FlightServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchFlights",
			Handler:    _FlightService_SearchFlights_Handler,
		},
		{
			MethodName: "GetFlightDetails",
			Handler:    _FlightService_GetFlightDetails_Handler,
		},
		{
			MethodName: "InternalLockSeat",
			Handler:    _FlightService_InternalLockSeat_Handler,
		},
		{
			MethodName: "InternalUnlockSeat",
			Handler:    _FlightService_InternalUnlockSeat_Handler,
		},
		{
			MethodName: "GetFlightSeats",
			Handler:    _FlightService_GetFlightSeats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/travelohi/v1/flight/flight.proto",
}
