services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: travelohi_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../database/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    networks:
      - travelohi-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d travelohi_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  memcached:
    image: memcached:1.6-alpine
    ports:
      - "11211:11211"
    networks:
      - travelohi-net

  # Microservices
  auth-service:
    build:
      context: .
      dockerfile: deployments/auth.Dockerfile
    ports:
      - "50051:50051"
    environment:
      - DB_URL=postgres://root:secretpassword@postgres:5432/travelohi_db?sslmode=disable
      - MEMCACHED_URL=memcached:11211
      - JWT_SECRET=your-super-secret-key
    depends_on:
      postgres:
        condition: service_healthy
      memcached:
        condition: service_started
    networks:
      - travelohi-net

  account-service:
    build:
      context: .
      dockerfile: deployments/account.Dockerfile
    ports:
      - "50052:50052"
    environment:
      - DB_URL=postgres://root:secretpassword@postgres:5432/travelohi_db?sslmode=disable
      - MEMCACHED_URL=memcached:11211
      - JWT_SECRET=your-super-secret-key
    depends_on:
      postgres:
        condition: service_healthy
      memcached:
        condition: service_started
    networks:
      - travelohi-net
  hotel-service:
    build:
      context: .
      dockerfile: deployments/hotel.Dockerfile
    ports:
      - "50053:50053"
    environment:
      - DB_URL=postgres://root:secretpassword@postgres:5432/travelohi_db?sslmode=disable
      - MEMCACHED_URL=memcached:11211
      - JWT_SECRET=your-super-secret-key
    depends_on:
      postgres:
        condition: service_healthy
      memcached:
        condition: service_started
    networks:
      - travelohi-net

  flight-service:
    build:
      context: .
      dockerfile: deployments/flight.Dockerfile
    ports:
      - "50054:50054"
    environment:
      - DB_URL=postgres://root:secretpassword@postgres:5432/travelohi_db?sslmode=disable
      - MEMCACHED_URL=memcached:11211
      - JWT_SECRET=your-super-secret-key
    depends_on:
      postgres:
        condition: service_healthy
      memcached:
        condition: service_started
    networks:
      - travelohi-net

  cart-service:
    build:
      context: .
      dockerfile: deployments/cart.Dockerfile
    ports:
      - "50055:50055"
    environment:
      - DB_URL=postgres://root:secretpassword@postgres:5432/travelohi_db?sslmode=disable
      - MEMCACHED_URL=memcached:11211
      - JWT_SECRET=your-super-secret-key
      - FLIGHT_SERVICE_URL=flight-service:50054
      - ACCOUNT_SERVICE_URL=account-service:50052
    depends_on:
      postgres:
        condition: service_healthy
      memcached:
        condition: service_started
    networks:
      - travelohi-net

  admin-service:
    build:
      context: .
      dockerfile: deployments/admin.Dockerfile
    ports:
      - "50056:50056"
    environment:
      - DB_URL=postgres://root:secretpassword@postgres:5432/travelohi_db?sslmode=disable
      - MEMCACHED_URL=memcached:11211
      - JWT_SECRET=your-super-secret-key
    depends_on:
      postgres:
        condition: service_healthy
      memcached:
        condition: service_started
    networks:
      - travelohi-net

  telemetry-service:
    build:
      context: .
      dockerfile: deployments/telemetry.Dockerfile
    ports:
      - "50057:50057"
    environment:
      - DB_URL=postgres://root:secretpassword@postgres:5432/travelohi_db?sslmode=disable
      - MEMCACHED_URL=memcached:11211
      - JWT_SECRET=your-super-secret-key
    depends_on:
      postgres:
        condition: service_healthy
      memcached:
        condition: service_started
    networks:
      - travelohi-net

  communication-service:
    build:
      context: .
      dockerfile: deployments/communication.Dockerfile
    ports:
      - "50058:50058"
    environment:
      - DB_URL=postgres://root:secretpassword@postgres:5432/travelohi_db?sslmode=disable
      - MEMCACHED_URL=memcached:11211
      - JWT_SECRET=your-super-secret-key
    depends_on:
      postgres:
        condition: service_healthy
      memcached:
        condition: service_started
    networks:
      - travelohi-net

  game-service:
    build:
      context: .
      dockerfile: deployments/game.Dockerfile
    ports:
      - "50059:50059"
    environment:
      - DB_URL=postgres://root:secretpassword@postgres:5432/travelohi_db?sslmode=disable
      - MEMCACHED_URL=memcached:11211
      - JWT_SECRET=your-super-secret-key
      - PORT=50059
    depends_on:
      postgres:
        condition: service_healthy
      memcached:
        condition: service_started
    networks:
      - travelohi-net

  # Envoy / API Gateway
  envoy:
    image: envoyproxy/envoy:v1.27-latest
    ports:
      - "8080:8080"
      - "9901:9901" #  for admin
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    depends_on:
      - auth-service
      - account-service
      - hotel-service
      - flight-service
      - cart-service
      - admin-service
      - telemetry-service
      - communication-service
      - game-service
    networks:
      - travelohi-net

  # Database Seeder
  seeder:
    build:
      context: .
      dockerfile: deployments/seeder.Dockerfile
    environment:
      - DB_URL=postgres://root:secretpassword@postgres:5432/travelohi_db?sslmode=disable
      - MEMCACHED_URL=memcached:11211
    depends_on:
      postgres:
        condition: service_healthy
      memcached:
        condition: service_started
    networks:
      - travelohi-net

networks:
  travelohi-net:
    driver: bridge
volumes:
  pgdata:
