// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "travelohi/v1/communication/communication.proto" (package "travelohi.v1.communication", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message travelohi.v1.communication.StreamChatRequest
 */
export interface StreamChatRequest {
    /**
     * @generated from protobuf field: string conversation_id = 1
     */
    conversationId: string;
    /**
     * @generated from protobuf field: string user_id = 2
     */
    userId: string;
}
/**
 * @generated from protobuf message travelohi.v1.communication.SendEventResponse
 */
export interface SendEventResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
    /**
     * @generated from protobuf field: string message_id = 2
     */
    messageId: string;
    /**
     * @generated from protobuf field: string timestamp = 3
     */
    timestamp: string;
}
/**
 * @generated from protobuf message travelohi.v1.communication.ChatEvent
 */
export interface ChatEvent {
    /**
     * @generated from protobuf field: string conversation_id = 1
     */
    conversationId: string;
    /**
     * @generated from protobuf field: string sender_id = 2
     */
    senderId: string;
    /**
     * @generated from protobuf oneof: event_payload
     */
    eventPayload: {
        oneofKind: "message";
        /**
         * @generated from protobuf field: travelohi.v1.communication.MessagePayload message = 3
         */
        message: MessagePayload;
    } | {
        oneofKind: "typingIndicator";
        /**
         * @generated from protobuf field: travelohi.v1.communication.TypingIndicatorPayload typing_indicator = 4
         */
        typingIndicator: TypingIndicatorPayload;
    } | {
        oneofKind: "readReceipt";
        /**
         * @generated from protobuf field: travelohi.v1.communication.ReadReceiptPayload read_receipt = 5
         */
        readReceipt: ReadReceiptPayload;
    } | {
        oneofKind: "conversationClosed";
        /**
         * @generated from protobuf field: travelohi.v1.communication.ConversationClosedPayload conversation_closed = 6
         */
        conversationClosed: ConversationClosedPayload;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message travelohi.v1.communication.MessagePayload
 */
export interface MessagePayload {
    /**
     * @generated from protobuf field: string message_id = 1
     */
    messageId: string;
    /**
     * @generated from protobuf field: string content = 2
     */
    content: string;
    /**
     * @generated from protobuf field: string timestamp = 3
     */
    timestamp: string;
    /**
     * @generated from protobuf field: string sender_id = 4
     */
    senderId: string;
    /**
     * @generated from protobuf field: string status = 5
     */
    status: string; // sent, seen}
/**
 * @generated from protobuf message travelohi.v1.communication.TypingIndicatorPayload
 */
export interface TypingIndicatorPayload {
    /**
     * @generated from protobuf field: bool is_typing = 1
     */
    isTyping: boolean;
}
/**
 * @generated from protobuf message travelohi.v1.communication.ReadReceiptPayload
 */
export interface ReadReceiptPayload {
    /**
     * @generated from protobuf field: string message_id = 1
     */
    messageId: string;
    /**
     * @generated from protobuf field: string new_status = 2
     */
    newStatus: string; // seen}
/**
 * @generated from protobuf message travelohi.v1.communication.GetChatHistoryRequest
 */
export interface GetChatHistoryRequest {
    /**
     * @generated from protobuf field: string conversation_id = 1
     */
    conversationId: string;
    /**
     * @generated from protobuf field: int32 limit = 2
     */
    limit: number; // buat infinite scrolling    /**
     * @generated from protobuf field: int32 offset = 3
     */
    offset: number;
}
/**
 * @generated from protobuf message travelohi.v1.communication.GetChatHistoryResponse
 */
export interface GetChatHistoryResponse {
    /**
     * @generated from protobuf field: repeated travelohi.v1.communication.MessagePayload messages = 1
     */
    messages: MessagePayload[];
}
/**
 * Admin Dashboard
 *
 * @generated from protobuf message travelohi.v1.communication.GetActiveConversationsRequest
 */
export interface GetActiveConversationsRequest {
    /**
     * @generated from protobuf field: string search_query = 1
     */
    searchQuery: string;
    /**
     * @generated from protobuf field: int32 limit = 2
     */
    limit: number;
    /**
     * @generated from protobuf field: int32 offset = 3
     */
    offset: number;
}
/**
 * @generated from protobuf message travelohi.v1.communication.ConversationPreview
 */
export interface ConversationPreview {
    /**
     * @generated from protobuf field: string conversation_id = 1
     */
    conversationId: string;
    /**
     * @generated from protobuf field: string user_id = 2
     */
    userId: string;
    /**
     * @generated from protobuf field: string full_name = 3
     */
    fullName: string;
    /**
     * @generated from protobuf field: string latest_message_content = 4
     */
    latestMessageContent: string;
    /**
     * @generated from protobuf field: string latest_message_timestamp = 5
     */
    latestMessageTimestamp: string;
    /**
     * @generated from protobuf field: int32 unread_count = 6
     */
    unreadCount: number;
    /**
     * @generated from protobuf field: string profile_picture_url = 7
     */
    profilePictureUrl: string;
}
/**
 * @generated from protobuf message travelohi.v1.communication.GetActiveConversationsResponse
 */
export interface GetActiveConversationsResponse {
    /**
     * @generated from protobuf field: repeated travelohi.v1.communication.ConversationPreview conversations = 1
     */
    conversations: ConversationPreview[];
    /**
     * @generated from protobuf field: int32 total_active = 2
     */
    totalActive: number;
}
/**
 * @generated from protobuf message travelohi.v1.communication.GetOrCreateConversationRequest
 */
export interface GetOrCreateConversationRequest {
    /**
     * @generated from protobuf field: string user_id = 1
     */
    userId: string;
    /**
     * @generated from protobuf field: bool create_if_not_exists = 2
     */
    createIfNotExists: boolean;
}
/**
 * @generated from protobuf message travelohi.v1.communication.GetOrCreateConversationResponse
 */
export interface GetOrCreateConversationResponse {
    /**
     * @generated from protobuf field: string conversation_id = 1
     */
    conversationId: string;
}
/**
 * @generated from protobuf message travelohi.v1.communication.CloseConversationRequest
 */
export interface CloseConversationRequest {
    /**
     * @generated from protobuf field: string conversation_id = 1
     */
    conversationId: string;
}
/**
 * @generated from protobuf message travelohi.v1.communication.CloseConversationResponse
 */
export interface CloseConversationResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
}
/**
 * @generated from protobuf message travelohi.v1.communication.ConversationClosedPayload
 */
export interface ConversationClosedPayload {
}
// @generated message type with reflection information, may provide speed optimized methods
class StreamChatRequest$Type extends MessageType<StreamChatRequest> {
    constructor() {
        super("travelohi.v1.communication.StreamChatRequest", [
            { no: 1, name: "conversation_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<StreamChatRequest>): StreamChatRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.conversationId = "";
        message.userId = "";
        if (value !== undefined)
            reflectionMergePartial<StreamChatRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: StreamChatRequest): StreamChatRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string conversation_id */ 1:
                    message.conversationId = reader.string();
                    break;
                case /* string user_id */ 2:
                    message.userId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: StreamChatRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string conversation_id = 1; */
        if (message.conversationId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.conversationId);
        /* string user_id = 2; */
        if (message.userId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.userId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.communication.StreamChatRequest
 */
export const StreamChatRequest = new StreamChatRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SendEventResponse$Type extends MessageType<SendEventResponse> {
    constructor() {
        super("travelohi.v1.communication.SendEventResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "message_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "timestamp", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SendEventResponse>): SendEventResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        message.messageId = "";
        message.timestamp = "";
        if (value !== undefined)
            reflectionMergePartial<SendEventResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SendEventResponse): SendEventResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                case /* string message_id */ 2:
                    message.messageId = reader.string();
                    break;
                case /* string timestamp */ 3:
                    message.timestamp = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SendEventResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        /* string message_id = 2; */
        if (message.messageId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.messageId);
        /* string timestamp = 3; */
        if (message.timestamp !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.timestamp);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.communication.SendEventResponse
 */
export const SendEventResponse = new SendEventResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ChatEvent$Type extends MessageType<ChatEvent> {
    constructor() {
        super("travelohi.v1.communication.ChatEvent", [
            { no: 1, name: "conversation_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "sender_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "message", kind: "message", oneof: "eventPayload", T: () => MessagePayload },
            { no: 4, name: "typing_indicator", kind: "message", oneof: "eventPayload", T: () => TypingIndicatorPayload },
            { no: 5, name: "read_receipt", kind: "message", oneof: "eventPayload", T: () => ReadReceiptPayload },
            { no: 6, name: "conversation_closed", kind: "message", oneof: "eventPayload", T: () => ConversationClosedPayload }
        ]);
    }
    create(value?: PartialMessage<ChatEvent>): ChatEvent {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.conversationId = "";
        message.senderId = "";
        message.eventPayload = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<ChatEvent>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ChatEvent): ChatEvent {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string conversation_id */ 1:
                    message.conversationId = reader.string();
                    break;
                case /* string sender_id */ 2:
                    message.senderId = reader.string();
                    break;
                case /* travelohi.v1.communication.MessagePayload message */ 3:
                    message.eventPayload = {
                        oneofKind: "message",
                        message: MessagePayload.internalBinaryRead(reader, reader.uint32(), options, (message.eventPayload as any).message)
                    };
                    break;
                case /* travelohi.v1.communication.TypingIndicatorPayload typing_indicator */ 4:
                    message.eventPayload = {
                        oneofKind: "typingIndicator",
                        typingIndicator: TypingIndicatorPayload.internalBinaryRead(reader, reader.uint32(), options, (message.eventPayload as any).typingIndicator)
                    };
                    break;
                case /* travelohi.v1.communication.ReadReceiptPayload read_receipt */ 5:
                    message.eventPayload = {
                        oneofKind: "readReceipt",
                        readReceipt: ReadReceiptPayload.internalBinaryRead(reader, reader.uint32(), options, (message.eventPayload as any).readReceipt)
                    };
                    break;
                case /* travelohi.v1.communication.ConversationClosedPayload conversation_closed */ 6:
                    message.eventPayload = {
                        oneofKind: "conversationClosed",
                        conversationClosed: ConversationClosedPayload.internalBinaryRead(reader, reader.uint32(), options, (message.eventPayload as any).conversationClosed)
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ChatEvent, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string conversation_id = 1; */
        if (message.conversationId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.conversationId);
        /* string sender_id = 2; */
        if (message.senderId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.senderId);
        /* travelohi.v1.communication.MessagePayload message = 3; */
        if (message.eventPayload.oneofKind === "message")
            MessagePayload.internalBinaryWrite(message.eventPayload.message, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* travelohi.v1.communication.TypingIndicatorPayload typing_indicator = 4; */
        if (message.eventPayload.oneofKind === "typingIndicator")
            TypingIndicatorPayload.internalBinaryWrite(message.eventPayload.typingIndicator, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* travelohi.v1.communication.ReadReceiptPayload read_receipt = 5; */
        if (message.eventPayload.oneofKind === "readReceipt")
            ReadReceiptPayload.internalBinaryWrite(message.eventPayload.readReceipt, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* travelohi.v1.communication.ConversationClosedPayload conversation_closed = 6; */
        if (message.eventPayload.oneofKind === "conversationClosed")
            ConversationClosedPayload.internalBinaryWrite(message.eventPayload.conversationClosed, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.communication.ChatEvent
 */
export const ChatEvent = new ChatEvent$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MessagePayload$Type extends MessageType<MessagePayload> {
    constructor() {
        super("travelohi.v1.communication.MessagePayload", [
            { no: 1, name: "message_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "content", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "timestamp", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "sender_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "status", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<MessagePayload>): MessagePayload {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.messageId = "";
        message.content = "";
        message.timestamp = "";
        message.senderId = "";
        message.status = "";
        if (value !== undefined)
            reflectionMergePartial<MessagePayload>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MessagePayload): MessagePayload {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string message_id */ 1:
                    message.messageId = reader.string();
                    break;
                case /* string content */ 2:
                    message.content = reader.string();
                    break;
                case /* string timestamp */ 3:
                    message.timestamp = reader.string();
                    break;
                case /* string sender_id */ 4:
                    message.senderId = reader.string();
                    break;
                case /* string status */ 5:
                    message.status = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MessagePayload, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string message_id = 1; */
        if (message.messageId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.messageId);
        /* string content = 2; */
        if (message.content !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.content);
        /* string timestamp = 3; */
        if (message.timestamp !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.timestamp);
        /* string sender_id = 4; */
        if (message.senderId !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.senderId);
        /* string status = 5; */
        if (message.status !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.status);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.communication.MessagePayload
 */
export const MessagePayload = new MessagePayload$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TypingIndicatorPayload$Type extends MessageType<TypingIndicatorPayload> {
    constructor() {
        super("travelohi.v1.communication.TypingIndicatorPayload", [
            { no: 1, name: "is_typing", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<TypingIndicatorPayload>): TypingIndicatorPayload {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.isTyping = false;
        if (value !== undefined)
            reflectionMergePartial<TypingIndicatorPayload>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TypingIndicatorPayload): TypingIndicatorPayload {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool is_typing */ 1:
                    message.isTyping = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TypingIndicatorPayload, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool is_typing = 1; */
        if (message.isTyping !== false)
            writer.tag(1, WireType.Varint).bool(message.isTyping);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.communication.TypingIndicatorPayload
 */
export const TypingIndicatorPayload = new TypingIndicatorPayload$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ReadReceiptPayload$Type extends MessageType<ReadReceiptPayload> {
    constructor() {
        super("travelohi.v1.communication.ReadReceiptPayload", [
            { no: 1, name: "message_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "new_status", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ReadReceiptPayload>): ReadReceiptPayload {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.messageId = "";
        message.newStatus = "";
        if (value !== undefined)
            reflectionMergePartial<ReadReceiptPayload>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ReadReceiptPayload): ReadReceiptPayload {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string message_id */ 1:
                    message.messageId = reader.string();
                    break;
                case /* string new_status */ 2:
                    message.newStatus = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ReadReceiptPayload, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string message_id = 1; */
        if (message.messageId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.messageId);
        /* string new_status = 2; */
        if (message.newStatus !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.newStatus);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.communication.ReadReceiptPayload
 */
export const ReadReceiptPayload = new ReadReceiptPayload$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetChatHistoryRequest$Type extends MessageType<GetChatHistoryRequest> {
    constructor() {
        super("travelohi.v1.communication.GetChatHistoryRequest", [
            { no: 1, name: "conversation_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "limit", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "offset", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<GetChatHistoryRequest>): GetChatHistoryRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.conversationId = "";
        message.limit = 0;
        message.offset = 0;
        if (value !== undefined)
            reflectionMergePartial<GetChatHistoryRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetChatHistoryRequest): GetChatHistoryRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string conversation_id */ 1:
                    message.conversationId = reader.string();
                    break;
                case /* int32 limit */ 2:
                    message.limit = reader.int32();
                    break;
                case /* int32 offset */ 3:
                    message.offset = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetChatHistoryRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string conversation_id = 1; */
        if (message.conversationId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.conversationId);
        /* int32 limit = 2; */
        if (message.limit !== 0)
            writer.tag(2, WireType.Varint).int32(message.limit);
        /* int32 offset = 3; */
        if (message.offset !== 0)
            writer.tag(3, WireType.Varint).int32(message.offset);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.communication.GetChatHistoryRequest
 */
export const GetChatHistoryRequest = new GetChatHistoryRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetChatHistoryResponse$Type extends MessageType<GetChatHistoryResponse> {
    constructor() {
        super("travelohi.v1.communication.GetChatHistoryResponse", [
            { no: 1, name: "messages", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => MessagePayload }
        ]);
    }
    create(value?: PartialMessage<GetChatHistoryResponse>): GetChatHistoryResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.messages = [];
        if (value !== undefined)
            reflectionMergePartial<GetChatHistoryResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetChatHistoryResponse): GetChatHistoryResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated travelohi.v1.communication.MessagePayload messages */ 1:
                    message.messages.push(MessagePayload.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetChatHistoryResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated travelohi.v1.communication.MessagePayload messages = 1; */
        for (let i = 0; i < message.messages.length; i++)
            MessagePayload.internalBinaryWrite(message.messages[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.communication.GetChatHistoryResponse
 */
export const GetChatHistoryResponse = new GetChatHistoryResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetActiveConversationsRequest$Type extends MessageType<GetActiveConversationsRequest> {
    constructor() {
        super("travelohi.v1.communication.GetActiveConversationsRequest", [
            { no: 1, name: "search_query", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "limit", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "offset", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<GetActiveConversationsRequest>): GetActiveConversationsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.searchQuery = "";
        message.limit = 0;
        message.offset = 0;
        if (value !== undefined)
            reflectionMergePartial<GetActiveConversationsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetActiveConversationsRequest): GetActiveConversationsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string search_query */ 1:
                    message.searchQuery = reader.string();
                    break;
                case /* int32 limit */ 2:
                    message.limit = reader.int32();
                    break;
                case /* int32 offset */ 3:
                    message.offset = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetActiveConversationsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string search_query = 1; */
        if (message.searchQuery !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.searchQuery);
        /* int32 limit = 2; */
        if (message.limit !== 0)
            writer.tag(2, WireType.Varint).int32(message.limit);
        /* int32 offset = 3; */
        if (message.offset !== 0)
            writer.tag(3, WireType.Varint).int32(message.offset);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.communication.GetActiveConversationsRequest
 */
export const GetActiveConversationsRequest = new GetActiveConversationsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ConversationPreview$Type extends MessageType<ConversationPreview> {
    constructor() {
        super("travelohi.v1.communication.ConversationPreview", [
            { no: 1, name: "conversation_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "full_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "latest_message_content", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "latest_message_timestamp", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "unread_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 7, name: "profile_picture_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ConversationPreview>): ConversationPreview {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.conversationId = "";
        message.userId = "";
        message.fullName = "";
        message.latestMessageContent = "";
        message.latestMessageTimestamp = "";
        message.unreadCount = 0;
        message.profilePictureUrl = "";
        if (value !== undefined)
            reflectionMergePartial<ConversationPreview>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ConversationPreview): ConversationPreview {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string conversation_id */ 1:
                    message.conversationId = reader.string();
                    break;
                case /* string user_id */ 2:
                    message.userId = reader.string();
                    break;
                case /* string full_name */ 3:
                    message.fullName = reader.string();
                    break;
                case /* string latest_message_content */ 4:
                    message.latestMessageContent = reader.string();
                    break;
                case /* string latest_message_timestamp */ 5:
                    message.latestMessageTimestamp = reader.string();
                    break;
                case /* int32 unread_count */ 6:
                    message.unreadCount = reader.int32();
                    break;
                case /* string profile_picture_url */ 7:
                    message.profilePictureUrl = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ConversationPreview, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string conversation_id = 1; */
        if (message.conversationId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.conversationId);
        /* string user_id = 2; */
        if (message.userId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.userId);
        /* string full_name = 3; */
        if (message.fullName !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.fullName);
        /* string latest_message_content = 4; */
        if (message.latestMessageContent !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.latestMessageContent);
        /* string latest_message_timestamp = 5; */
        if (message.latestMessageTimestamp !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.latestMessageTimestamp);
        /* int32 unread_count = 6; */
        if (message.unreadCount !== 0)
            writer.tag(6, WireType.Varint).int32(message.unreadCount);
        /* string profile_picture_url = 7; */
        if (message.profilePictureUrl !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.profilePictureUrl);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.communication.ConversationPreview
 */
export const ConversationPreview = new ConversationPreview$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetActiveConversationsResponse$Type extends MessageType<GetActiveConversationsResponse> {
    constructor() {
        super("travelohi.v1.communication.GetActiveConversationsResponse", [
            { no: 1, name: "conversations", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => ConversationPreview },
            { no: 2, name: "total_active", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<GetActiveConversationsResponse>): GetActiveConversationsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.conversations = [];
        message.totalActive = 0;
        if (value !== undefined)
            reflectionMergePartial<GetActiveConversationsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetActiveConversationsResponse): GetActiveConversationsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated travelohi.v1.communication.ConversationPreview conversations */ 1:
                    message.conversations.push(ConversationPreview.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* int32 total_active */ 2:
                    message.totalActive = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetActiveConversationsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated travelohi.v1.communication.ConversationPreview conversations = 1; */
        for (let i = 0; i < message.conversations.length; i++)
            ConversationPreview.internalBinaryWrite(message.conversations[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* int32 total_active = 2; */
        if (message.totalActive !== 0)
            writer.tag(2, WireType.Varint).int32(message.totalActive);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.communication.GetActiveConversationsResponse
 */
export const GetActiveConversationsResponse = new GetActiveConversationsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetOrCreateConversationRequest$Type extends MessageType<GetOrCreateConversationRequest> {
    constructor() {
        super("travelohi.v1.communication.GetOrCreateConversationRequest", [
            { no: 1, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "create_if_not_exists", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<GetOrCreateConversationRequest>): GetOrCreateConversationRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.userId = "";
        message.createIfNotExists = false;
        if (value !== undefined)
            reflectionMergePartial<GetOrCreateConversationRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetOrCreateConversationRequest): GetOrCreateConversationRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string user_id */ 1:
                    message.userId = reader.string();
                    break;
                case /* bool create_if_not_exists */ 2:
                    message.createIfNotExists = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetOrCreateConversationRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string user_id = 1; */
        if (message.userId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.userId);
        /* bool create_if_not_exists = 2; */
        if (message.createIfNotExists !== false)
            writer.tag(2, WireType.Varint).bool(message.createIfNotExists);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.communication.GetOrCreateConversationRequest
 */
export const GetOrCreateConversationRequest = new GetOrCreateConversationRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetOrCreateConversationResponse$Type extends MessageType<GetOrCreateConversationResponse> {
    constructor() {
        super("travelohi.v1.communication.GetOrCreateConversationResponse", [
            { no: 1, name: "conversation_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetOrCreateConversationResponse>): GetOrCreateConversationResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.conversationId = "";
        if (value !== undefined)
            reflectionMergePartial<GetOrCreateConversationResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetOrCreateConversationResponse): GetOrCreateConversationResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string conversation_id */ 1:
                    message.conversationId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetOrCreateConversationResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string conversation_id = 1; */
        if (message.conversationId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.conversationId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.communication.GetOrCreateConversationResponse
 */
export const GetOrCreateConversationResponse = new GetOrCreateConversationResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CloseConversationRequest$Type extends MessageType<CloseConversationRequest> {
    constructor() {
        super("travelohi.v1.communication.CloseConversationRequest", [
            { no: 1, name: "conversation_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CloseConversationRequest>): CloseConversationRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.conversationId = "";
        if (value !== undefined)
            reflectionMergePartial<CloseConversationRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CloseConversationRequest): CloseConversationRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string conversation_id */ 1:
                    message.conversationId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CloseConversationRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string conversation_id = 1; */
        if (message.conversationId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.conversationId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.communication.CloseConversationRequest
 */
export const CloseConversationRequest = new CloseConversationRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CloseConversationResponse$Type extends MessageType<CloseConversationResponse> {
    constructor() {
        super("travelohi.v1.communication.CloseConversationResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<CloseConversationResponse>): CloseConversationResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        if (value !== undefined)
            reflectionMergePartial<CloseConversationResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CloseConversationResponse): CloseConversationResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CloseConversationResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.communication.CloseConversationResponse
 */
export const CloseConversationResponse = new CloseConversationResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ConversationClosedPayload$Type extends MessageType<ConversationClosedPayload> {
    constructor() {
        super("travelohi.v1.communication.ConversationClosedPayload", []);
    }
    create(value?: PartialMessage<ConversationClosedPayload>): ConversationClosedPayload {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<ConversationClosedPayload>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ConversationClosedPayload): ConversationClosedPayload {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ConversationClosedPayload, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message travelohi.v1.communication.ConversationClosedPayload
 */
export const ConversationClosedPayload = new ConversationClosedPayload$Type();
/**
 * @generated ServiceType for protobuf service travelohi.v1.communication.CommunicationService
 */
export const CommunicationService = new ServiceType("travelohi.v1.communication.CommunicationService", [
    { name: "StreamChat", serverStreaming: true, options: {}, I: StreamChatRequest, O: ChatEvent },
    { name: "SendEvent", options: {}, I: ChatEvent, O: SendEventResponse },
    { name: "GetChatHistory", options: {}, I: GetChatHistoryRequest, O: GetChatHistoryResponse },
    { name: "GetActiveConversations", options: {}, I: GetActiveConversationsRequest, O: GetActiveConversationsResponse },
    { name: "GetOrCreateConversation", options: {}, I: GetOrCreateConversationRequest, O: GetOrCreateConversationResponse },
    { name: "CloseConversation", options: {}, I: CloseConversationRequest, O: CloseConversationResponse }
]);
