// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/travelohi/v1/auth/auth.proto

package authpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Email               string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password            string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	FirstName           string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName            string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Dob                 string                 `protobuf:"bytes,5,opt,name=dob,proto3" json:"dob,omitempty"`
	Gender              string                 `protobuf:"bytes,6,opt,name=gender,proto3" json:"gender,omitempty"`
	SubscribeNewsletter bool                   `protobuf:"varint,7,opt,name=subscribe_newsletter,json=subscribeNewsletter,proto3" json:"subscribe_newsletter,omitempty"`
	CaptchaToken        string                 `protobuf:"bytes,8,opt,name=captcha_token,json=captchaToken,proto3" json:"captcha_token,omitempty"`
	SecurityQuestionId  int32                  `protobuf:"varint,9,opt,name=security_question_id,json=securityQuestionId,proto3" json:"security_question_id,omitempty"`
	SecurityAnswer      string                 `protobuf:"bytes,10,opt,name=security_answer,json=securityAnswer,proto3" json:"security_answer,omitempty"`
	ProfilePicture      string                 `protobuf:"bytes,11,opt,name=profile_picture,json=profilePicture,proto3" json:"profile_picture,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_travelohi_v1_auth_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_travelohi_v1_auth_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_travelohi_v1_auth_auth_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *RegisterRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *RegisterRequest) GetDob() string {
	if x != nil {
		return x.Dob
	}
	return ""
}

func (x *RegisterRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *RegisterRequest) GetSubscribeNewsletter() bool {
	if x != nil {
		return x.SubscribeNewsletter
	}
	return false
}

func (x *RegisterRequest) GetCaptchaToken() string {
	if x != nil {
		return x.CaptchaToken
	}
	return ""
}

func (x *RegisterRequest) GetSecurityQuestionId() int32 {
	if x != nil {
		return x.SecurityQuestionId
	}
	return 0
}

func (x *RegisterRequest) GetSecurityAnswer() string {
	if x != nil {
		return x.SecurityAnswer
	}
	return ""
}

func (x *RegisterRequest) GetProfilePicture() string {
	if x != nil {
		return x.ProfilePicture
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	CaptchaToken  string                 `protobuf:"bytes,3,opt,name=captcha_token,json=captchaToken,proto3" json:"captcha_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_travelohi_v1_auth_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_travelohi_v1_auth_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_travelohi_v1_auth_auth_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetCaptchaToken() string {
	if x != nil {
		return x.CaptchaToken
	}
	return ""
}

type SendOTPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendOTPRequest) Reset() {
	*x = SendOTPRequest{}
	mi := &file_proto_travelohi_v1_auth_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendOTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOTPRequest) ProtoMessage() {}

func (x *SendOTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_travelohi_v1_auth_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOTPRequest.ProtoReflect.Descriptor instead.
func (*SendOTPRequest) Descriptor() ([]byte, []int) {
	return file_proto_travelohi_v1_auth_auth_proto_rawDescGZIP(), []int{2}
}

func (x *SendOTPRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type SendOTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendOTPResponse) Reset() {
	*x = SendOTPResponse{}
	mi := &file_proto_travelohi_v1_auth_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendOTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOTPResponse) ProtoMessage() {}

func (x *SendOTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_travelohi_v1_auth_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOTPResponse.ProtoReflect.Descriptor instead.
func (*SendOTPResponse) Descriptor() ([]byte, []int) {
	return file_proto_travelohi_v1_auth_auth_proto_rawDescGZIP(), []int{3}
}

func (x *SendOTPResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendOTPResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LoginWithOTPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	OtpCode       string                 `protobuf:"bytes,2,opt,name=otp_code,json=otpCode,proto3" json:"otp_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginWithOTPRequest) Reset() {
	*x = LoginWithOTPRequest{}
	mi := &file_proto_travelohi_v1_auth_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginWithOTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginWithOTPRequest) ProtoMessage() {}

func (x *LoginWithOTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_travelohi_v1_auth_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginWithOTPRequest.ProtoReflect.Descriptor instead.
func (*LoginWithOTPRequest) Descriptor() ([]byte, []int) {
	return file_proto_travelohi_v1_auth_auth_proto_rawDescGZIP(), []int{4}
}

func (x *LoginWithOTPRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginWithOTPRequest) GetOtpCode() string {
	if x != nil {
		return x.OtpCode
	}
	return ""
}

// shared responses
type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"` // jwt disimpen disini buat frontend
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_proto_travelohi_v1_auth_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_travelohi_v1_auth_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_proto_travelohi_v1_auth_auth_proto_rawDescGZIP(), []int{5}
}

func (x *AuthResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *AuthResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ActivateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateAccountRequest) Reset() {
	*x = ActivateAccountRequest{}
	mi := &file_proto_travelohi_v1_auth_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateAccountRequest) ProtoMessage() {}

func (x *ActivateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_travelohi_v1_auth_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateAccountRequest.ProtoReflect.Descriptor instead.
func (*ActivateAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_travelohi_v1_auth_auth_proto_rawDescGZIP(), []int{6}
}

func (x *ActivateAccountRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ActivateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateAccountResponse) Reset() {
	*x = ActivateAccountResponse{}
	mi := &file_proto_travelohi_v1_auth_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateAccountResponse) ProtoMessage() {}

func (x *ActivateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_travelohi_v1_auth_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateAccountResponse.ProtoReflect.Descriptor instead.
func (*ActivateAccountResponse) Descriptor() ([]byte, []int) {
	return file_proto_travelohi_v1_auth_auth_proto_rawDescGZIP(), []int{7}
}

func (x *ActivateAccountResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ActivateAccountResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ResendActivationEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResendActivationEmailRequest) Reset() {
	*x = ResendActivationEmailRequest{}
	mi := &file_proto_travelohi_v1_auth_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResendActivationEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResendActivationEmailRequest) ProtoMessage() {}

func (x *ResendActivationEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_travelohi_v1_auth_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResendActivationEmailRequest.ProtoReflect.Descriptor instead.
func (*ResendActivationEmailRequest) Descriptor() ([]byte, []int) {
	return file_proto_travelohi_v1_auth_auth_proto_rawDescGZIP(), []int{8}
}

func (x *ResendActivationEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ResendActivationEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResendActivationEmailResponse) Reset() {
	*x = ResendActivationEmailResponse{}
	mi := &file_proto_travelohi_v1_auth_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResendActivationEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResendActivationEmailResponse) ProtoMessage() {}

func (x *ResendActivationEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_travelohi_v1_auth_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResendActivationEmailResponse.ProtoReflect.Descriptor instead.
func (*ResendActivationEmailResponse) Descriptor() ([]byte, []int) {
	return file_proto_travelohi_v1_auth_auth_proto_rawDescGZIP(), []int{9}
}

func (x *ResendActivationEmailResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResendActivationEmailResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_proto_travelohi_v1_auth_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_travelohi_v1_auth_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_proto_travelohi_v1_auth_auth_proto_rawDescGZIP(), []int{10}
}

func (x *LogoutRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_proto_travelohi_v1_auth_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_travelohi_v1_auth_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_proto_travelohi_v1_auth_auth_proto_rawDescGZIP(), []int{11}
}

func (x *LogoutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LogoutResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetSecurityQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	CaptchaToken  string                 `protobuf:"bytes,2,opt,name=captcha_token,json=captchaToken,proto3" json:"captcha_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecurityQuestionRequest) Reset() {
	*x = GetSecurityQuestionRequest{}
	mi := &file_proto_travelohi_v1_auth_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecurityQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecurityQuestionRequest) ProtoMessage() {}

func (x *GetSecurityQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_travelohi_v1_auth_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecurityQuestionRequest.ProtoReflect.Descriptor instead.
func (*GetSecurityQuestionRequest) Descriptor() ([]byte, []int) {
	return file_proto_travelohi_v1_auth_auth_proto_rawDescGZIP(), []int{12}
}

func (x *GetSecurityQuestionRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetSecurityQuestionRequest) GetCaptchaToken() string {
	if x != nil {
		return x.CaptchaToken
	}
	return ""
}

type GetSecurityQuestionResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SecurityQuestionId int32                  `protobuf:"varint,1,opt,name=security_question_id,json=securityQuestionId,proto3" json:"security_question_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetSecurityQuestionResponse) Reset() {
	*x = GetSecurityQuestionResponse{}
	mi := &file_proto_travelohi_v1_auth_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecurityQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecurityQuestionResponse) ProtoMessage() {}

func (x *GetSecurityQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_travelohi_v1_auth_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecurityQuestionResponse.ProtoReflect.Descriptor instead.
func (*GetSecurityQuestionResponse) Descriptor() ([]byte, []int) {
	return file_proto_travelohi_v1_auth_auth_proto_rawDescGZIP(), []int{13}
}

func (x *GetSecurityQuestionResponse) GetSecurityQuestionId() int32 {
	if x != nil {
		return x.SecurityQuestionId
	}
	return 0
}

type ResetPasswordRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Email              string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	SecurityAnswer     string                 `protobuf:"bytes,2,opt,name=security_answer,json=securityAnswer,proto3" json:"security_answer,omitempty"`
	NewPassword        string                 `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	SecurityQuestionId int32                  `protobuf:"varint,4,opt,name=security_question_id,json=securityQuestionId,proto3" json:"security_question_id,omitempty"`
	CaptchaToken       string                 `protobuf:"bytes,5,opt,name=captcha_token,json=captchaToken,proto3" json:"captcha_token,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ResetPasswordRequest) Reset() {
	*x = ResetPasswordRequest{}
	mi := &file_proto_travelohi_v1_auth_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordRequest) ProtoMessage() {}

func (x *ResetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_travelohi_v1_auth_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordRequest.ProtoReflect.Descriptor instead.
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_proto_travelohi_v1_auth_auth_proto_rawDescGZIP(), []int{14}
}

func (x *ResetPasswordRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ResetPasswordRequest) GetSecurityAnswer() string {
	if x != nil {
		return x.SecurityAnswer
	}
	return ""
}

func (x *ResetPasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

func (x *ResetPasswordRequest) GetSecurityQuestionId() int32 {
	if x != nil {
		return x.SecurityQuestionId
	}
	return 0
}

func (x *ResetPasswordRequest) GetCaptchaToken() string {
	if x != nil {
		return x.CaptchaToken
	}
	return ""
}

type CheckEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	CaptchaToken  string                 `protobuf:"bytes,2,opt,name=captcha_token,json=captchaToken,proto3" json:"captcha_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckEmailRequest) Reset() {
	*x = CheckEmailRequest{}
	mi := &file_proto_travelohi_v1_auth_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckEmailRequest) ProtoMessage() {}

func (x *CheckEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_travelohi_v1_auth_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckEmailRequest.ProtoReflect.Descriptor instead.
func (*CheckEmailRequest) Descriptor() ([]byte, []int) {
	return file_proto_travelohi_v1_auth_auth_proto_rawDescGZIP(), []int{15}
}

func (x *CheckEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CheckEmailRequest) GetCaptchaToken() string {
	if x != nil {
		return x.CaptchaToken
	}
	return ""
}

type CheckEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	IsActive      bool                   `protobuf:"varint,2,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckEmailResponse) Reset() {
	*x = CheckEmailResponse{}
	mi := &file_proto_travelohi_v1_auth_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckEmailResponse) ProtoMessage() {}

func (x *CheckEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_travelohi_v1_auth_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckEmailResponse.ProtoReflect.Descriptor instead.
func (*CheckEmailResponse) Descriptor() ([]byte, []int) {
	return file_proto_travelohi_v1_auth_auth_proto_rawDescGZIP(), []int{16}
}

func (x *CheckEmailResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *CheckEmailResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

var File_proto_travelohi_v1_auth_auth_proto protoreflect.FileDescriptor

const file_proto_travelohi_v1_auth_auth_proto_rawDesc = "" +
	"\n" +
	"\"proto/travelohi/v1/auth/auth.proto\x12\x11travelohi.v1.auth\"\x85\x03\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x10\n" +
	"\x03dob\x18\x05 \x01(\tR\x03dob\x12\x16\n" +
	"\x06gender\x18\x06 \x01(\tR\x06gender\x121\n" +
	"\x14subscribe_newsletter\x18\a \x01(\bR\x13subscribeNewsletter\x12#\n" +
	"\rcaptcha_token\x18\b \x01(\tR\fcaptchaToken\x120\n" +
	"\x14security_question_id\x18\t \x01(\x05R\x12securityQuestionId\x12'\n" +
	"\x0fsecurity_answer\x18\n" +
	" \x01(\tR\x0esecurityAnswer\x12'\n" +
	"\x0fprofile_picture\x18\v \x01(\tR\x0eprofilePicture\"e\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12#\n" +
	"\rcaptcha_token\x18\x03 \x01(\tR\fcaptchaToken\"&\n" +
	"\x0eSendOTPRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"E\n" +
	"\x0fSendOTPResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"F\n" +
	"\x13LoginWithOTPRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x19\n" +
	"\botp_code\x18\x02 \x01(\tR\aotpCode\"d\n" +
	"\fAuthResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\".\n" +
	"\x16ActivateAccountRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"M\n" +
	"\x17ActivateAccountResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"4\n" +
	"\x1cResendActivationEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"S\n" +
	"\x1dResendActivationEmailResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"(\n" +
	"\rLogoutRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"D\n" +
	"\x0eLogoutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"W\n" +
	"\x1aGetSecurityQuestionRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12#\n" +
	"\rcaptcha_token\x18\x02 \x01(\tR\fcaptchaToken\"O\n" +
	"\x1bGetSecurityQuestionResponse\x120\n" +
	"\x14security_question_id\x18\x01 \x01(\x05R\x12securityQuestionId\"\xcf\x01\n" +
	"\x14ResetPasswordRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12'\n" +
	"\x0fsecurity_answer\x18\x02 \x01(\tR\x0esecurityAnswer\x12!\n" +
	"\fnew_password\x18\x03 \x01(\tR\vnewPassword\x120\n" +
	"\x14security_question_id\x18\x04 \x01(\x05R\x12securityQuestionId\x12#\n" +
	"\rcaptcha_token\x18\x05 \x01(\tR\fcaptchaToken\"N\n" +
	"\x11CheckEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12#\n" +
	"\rcaptcha_token\x18\x02 \x01(\tR\fcaptchaToken\"I\n" +
	"\x12CheckEmailResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x1b\n" +
	"\tis_active\x18\x02 \x01(\bR\bisActive2\xc9\a\n" +
	"\vAuthService\x12K\n" +
	"\x05Login\x12\x1f.travelohi.v1.auth.LoginRequest\x1a\x1f.travelohi.v1.auth.AuthResponse\"\x00\x12R\n" +
	"\aSendOTP\x12!.travelohi.v1.auth.SendOTPRequest\x1a\".travelohi.v1.auth.SendOTPResponse\"\x00\x12Y\n" +
	"\fLoginWithOTP\x12&.travelohi.v1.auth.LoginWithOTPRequest\x1a\x1f.travelohi.v1.auth.AuthResponse\"\x00\x12Q\n" +
	"\bRegister\x12\".travelohi.v1.auth.RegisterRequest\x1a\x1f.travelohi.v1.auth.AuthResponse\"\x00\x12j\n" +
	"\x0fActivateAccount\x12).travelohi.v1.auth.ActivateAccountRequest\x1a*.travelohi.v1.auth.ActivateAccountResponse\"\x00\x12|\n" +
	"\x15ResendActivationEmail\x12/.travelohi.v1.auth.ResendActivationEmailRequest\x1a0.travelohi.v1.auth.ResendActivationEmailResponse\"\x00\x12O\n" +
	"\x06Logout\x12 .travelohi.v1.auth.LogoutRequest\x1a!.travelohi.v1.auth.LogoutResponse\"\x00\x12v\n" +
	"\x13GetSecurityQuestion\x12-.travelohi.v1.auth.GetSecurityQuestionRequest\x1a..travelohi.v1.auth.GetSecurityQuestionResponse\"\x00\x12[\n" +
	"\rResetPassword\x12'.travelohi.v1.auth.ResetPasswordRequest\x1a\x1f.travelohi.v1.auth.AuthResponse\"\x00\x12[\n" +
	"\n" +
	"CheckEmail\x12$.travelohi.v1.auth.CheckEmailRequest\x1a%.travelohi.v1.auth.CheckEmailResponse\"\x00B3Z1github.com/travelohi/backend/proto/auth/v1;authpbb\x06proto3"

var (
	file_proto_travelohi_v1_auth_auth_proto_rawDescOnce sync.Once
	file_proto_travelohi_v1_auth_auth_proto_rawDescData []byte
)

func file_proto_travelohi_v1_auth_auth_proto_rawDescGZIP() []byte {
	file_proto_travelohi_v1_auth_auth_proto_rawDescOnce.Do(func() {
		file_proto_travelohi_v1_auth_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_travelohi_v1_auth_auth_proto_rawDesc), len(file_proto_travelohi_v1_auth_auth_proto_rawDesc)))
	})
	return file_proto_travelohi_v1_auth_auth_proto_rawDescData
}

var file_proto_travelohi_v1_auth_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_travelohi_v1_auth_auth_proto_goTypes = []any{
	(*RegisterRequest)(nil),               // 0: travelohi.v1.auth.RegisterRequest
	(*LoginRequest)(nil),                  // 1: travelohi.v1.auth.LoginRequest
	(*SendOTPRequest)(nil),                // 2: travelohi.v1.auth.SendOTPRequest
	(*SendOTPResponse)(nil),               // 3: travelohi.v1.auth.SendOTPResponse
	(*LoginWithOTPRequest)(nil),           // 4: travelohi.v1.auth.LoginWithOTPRequest
	(*AuthResponse)(nil),                  // 5: travelohi.v1.auth.AuthResponse
	(*ActivateAccountRequest)(nil),        // 6: travelohi.v1.auth.ActivateAccountRequest
	(*ActivateAccountResponse)(nil),       // 7: travelohi.v1.auth.ActivateAccountResponse
	(*ResendActivationEmailRequest)(nil),  // 8: travelohi.v1.auth.ResendActivationEmailRequest
	(*ResendActivationEmailResponse)(nil), // 9: travelohi.v1.auth.ResendActivationEmailResponse
	(*LogoutRequest)(nil),                 // 10: travelohi.v1.auth.LogoutRequest
	(*LogoutResponse)(nil),                // 11: travelohi.v1.auth.LogoutResponse
	(*GetSecurityQuestionRequest)(nil),    // 12: travelohi.v1.auth.GetSecurityQuestionRequest
	(*GetSecurityQuestionResponse)(nil),   // 13: travelohi.v1.auth.GetSecurityQuestionResponse
	(*ResetPasswordRequest)(nil),          // 14: travelohi.v1.auth.ResetPasswordRequest
	(*CheckEmailRequest)(nil),             // 15: travelohi.v1.auth.CheckEmailRequest
	(*CheckEmailResponse)(nil),            // 16: travelohi.v1.auth.CheckEmailResponse
}
var file_proto_travelohi_v1_auth_auth_proto_depIdxs = []int32{
	1,  // 0: travelohi.v1.auth.AuthService.Login:input_type -> travelohi.v1.auth.LoginRequest
	2,  // 1: travelohi.v1.auth.AuthService.SendOTP:input_type -> travelohi.v1.auth.SendOTPRequest
	4,  // 2: travelohi.v1.auth.AuthService.LoginWithOTP:input_type -> travelohi.v1.auth.LoginWithOTPRequest
	0,  // 3: travelohi.v1.auth.AuthService.Register:input_type -> travelohi.v1.auth.RegisterRequest
	6,  // 4: travelohi.v1.auth.AuthService.ActivateAccount:input_type -> travelohi.v1.auth.ActivateAccountRequest
	8,  // 5: travelohi.v1.auth.AuthService.ResendActivationEmail:input_type -> travelohi.v1.auth.ResendActivationEmailRequest
	10, // 6: travelohi.v1.auth.AuthService.Logout:input_type -> travelohi.v1.auth.LogoutRequest
	12, // 7: travelohi.v1.auth.AuthService.GetSecurityQuestion:input_type -> travelohi.v1.auth.GetSecurityQuestionRequest
	14, // 8: travelohi.v1.auth.AuthService.ResetPassword:input_type -> travelohi.v1.auth.ResetPasswordRequest
	15, // 9: travelohi.v1.auth.AuthService.CheckEmail:input_type -> travelohi.v1.auth.CheckEmailRequest
	5,  // 10: travelohi.v1.auth.AuthService.Login:output_type -> travelohi.v1.auth.AuthResponse
	3,  // 11: travelohi.v1.auth.AuthService.SendOTP:output_type -> travelohi.v1.auth.SendOTPResponse
	5,  // 12: travelohi.v1.auth.AuthService.LoginWithOTP:output_type -> travelohi.v1.auth.AuthResponse
	5,  // 13: travelohi.v1.auth.AuthService.Register:output_type -> travelohi.v1.auth.AuthResponse
	7,  // 14: travelohi.v1.auth.AuthService.ActivateAccount:output_type -> travelohi.v1.auth.ActivateAccountResponse
	9,  // 15: travelohi.v1.auth.AuthService.ResendActivationEmail:output_type -> travelohi.v1.auth.ResendActivationEmailResponse
	11, // 16: travelohi.v1.auth.AuthService.Logout:output_type -> travelohi.v1.auth.LogoutResponse
	13, // 17: travelohi.v1.auth.AuthService.GetSecurityQuestion:output_type -> travelohi.v1.auth.GetSecurityQuestionResponse
	5,  // 18: travelohi.v1.auth.AuthService.ResetPassword:output_type -> travelohi.v1.auth.AuthResponse
	16, // 19: travelohi.v1.auth.AuthService.CheckEmail:output_type -> travelohi.v1.auth.CheckEmailResponse
	10, // [10:20] is the sub-list for method output_type
	0,  // [0:10] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_travelohi_v1_auth_auth_proto_init() }
func file_proto_travelohi_v1_auth_auth_proto_init() {
	if File_proto_travelohi_v1_auth_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_travelohi_v1_auth_auth_proto_rawDesc), len(file_proto_travelohi_v1_auth_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_travelohi_v1_auth_auth_proto_goTypes,
		DependencyIndexes: file_proto_travelohi_v1_auth_auth_proto_depIdxs,
		MessageInfos:      file_proto_travelohi_v1_auth_auth_proto_msgTypes,
	}.Build()
	File_proto_travelohi_v1_auth_auth_proto = out.File
	file_proto_travelohi_v1_auth_auth_proto_goTypes = nil
	file_proto_travelohi_v1_auth_auth_proto_depIdxs = nil
}
