// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.31.1
// source: proto/travelohi/v1/admin/admin.proto

package adminpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminService_InsertHotel_FullMethodName       = "/travelohi.v1.admin.AdminService/InsertHotel"
	AdminService_InsertAirline_FullMethodName     = "/travelohi.v1.admin.AdminService/InsertAirline"
	AdminService_CreatePromo_FullMethodName       = "/travelohi.v1.admin.AdminService/CreatePromo"
	AdminService_TogglePromoStatus_FullMethodName = "/travelohi.v1.admin.AdminService/TogglePromoStatus"
	AdminService_GetAllPromos_FullMethodName      = "/travelohi.v1.admin.AdminService/GetAllPromos"
	AdminService_GetAllUsers_FullMethodName       = "/travelohi.v1.admin.AdminService/GetAllUsers"
	AdminService_BanUser_FullMethodName           = "/travelohi.v1.admin.AdminService/BanUser"
	AdminService_SendBroadcast_FullMethodName     = "/travelohi.v1.admin.AdminService/SendBroadcast"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminServiceClient interface {
	// Inventory Ingestion
	InsertHotel(ctx context.Context, in *InsertHotelRequest, opts ...grpc.CallOption) (*AdminResponse, error)
	InsertAirline(ctx context.Context, in *InsertAirlineRequest, opts ...grpc.CallOption) (*AdminResponse, error)
	// Promo Management
	CreatePromo(ctx context.Context, in *CreatePromoRequest, opts ...grpc.CallOption) (*AdminResponse, error)
	TogglePromoStatus(ctx context.Context, in *TogglePromoRequest, opts ...grpc.CallOption) (*AdminResponse, error)
	GetAllPromos(ctx context.Context, in *GetAllPromosRequest, opts ...grpc.CallOption) (*GetAllPromosResponse, error)
	// User Management
	GetAllUsers(ctx context.Context, in *GetAllUsersRequest, opts ...grpc.CallOption) (*GetAllUsersResponse, error)
	BanUser(ctx context.Context, in *BanUserRequest, opts ...grpc.CallOption) (*AdminResponse, error)
	// Notification
	SendBroadcast(ctx context.Context, in *SendBroadcastRequest, opts ...grpc.CallOption) (*AdminResponse, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) InsertHotel(ctx context.Context, in *InsertHotelRequest, opts ...grpc.CallOption) (*AdminResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminResponse)
	err := c.cc.Invoke(ctx, AdminService_InsertHotel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) InsertAirline(ctx context.Context, in *InsertAirlineRequest, opts ...grpc.CallOption) (*AdminResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminResponse)
	err := c.cc.Invoke(ctx, AdminService_InsertAirline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) CreatePromo(ctx context.Context, in *CreatePromoRequest, opts ...grpc.CallOption) (*AdminResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminResponse)
	err := c.cc.Invoke(ctx, AdminService_CreatePromo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) TogglePromoStatus(ctx context.Context, in *TogglePromoRequest, opts ...grpc.CallOption) (*AdminResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminResponse)
	err := c.cc.Invoke(ctx, AdminService_TogglePromoStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetAllPromos(ctx context.Context, in *GetAllPromosRequest, opts ...grpc.CallOption) (*GetAllPromosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllPromosResponse)
	err := c.cc.Invoke(ctx, AdminService_GetAllPromos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetAllUsers(ctx context.Context, in *GetAllUsersRequest, opts ...grpc.CallOption) (*GetAllUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllUsersResponse)
	err := c.cc.Invoke(ctx, AdminService_GetAllUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) BanUser(ctx context.Context, in *BanUserRequest, opts ...grpc.CallOption) (*AdminResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminResponse)
	err := c.cc.Invoke(ctx, AdminService_BanUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) SendBroadcast(ctx context.Context, in *SendBroadcastRequest, opts ...grpc.CallOption) (*AdminResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminResponse)
	err := c.cc.Invoke(ctx, AdminService_SendBroadcast_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility.
type AdminServiceServer interface {
	// Inventory Ingestion
	InsertHotel(context.Context, *InsertHotelRequest) (*AdminResponse, error)
	InsertAirline(context.Context, *InsertAirlineRequest) (*AdminResponse, error)
	// Promo Management
	CreatePromo(context.Context, *CreatePromoRequest) (*AdminResponse, error)
	TogglePromoStatus(context.Context, *TogglePromoRequest) (*AdminResponse, error)
	GetAllPromos(context.Context, *GetAllPromosRequest) (*GetAllPromosResponse, error)
	// User Management
	GetAllUsers(context.Context, *GetAllUsersRequest) (*GetAllUsersResponse, error)
	BanUser(context.Context, *BanUserRequest) (*AdminResponse, error)
	// Notification
	SendBroadcast(context.Context, *SendBroadcastRequest) (*AdminResponse, error)
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServiceServer struct{}

func (UnimplementedAdminServiceServer) InsertHotel(context.Context, *InsertHotelRequest) (*AdminResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InsertHotel not implemented")
}
func (UnimplementedAdminServiceServer) InsertAirline(context.Context, *InsertAirlineRequest) (*AdminResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InsertAirline not implemented")
}
func (UnimplementedAdminServiceServer) CreatePromo(context.Context, *CreatePromoRequest) (*AdminResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePromo not implemented")
}
func (UnimplementedAdminServiceServer) TogglePromoStatus(context.Context, *TogglePromoRequest) (*AdminResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TogglePromoStatus not implemented")
}
func (UnimplementedAdminServiceServer) GetAllPromos(context.Context, *GetAllPromosRequest) (*GetAllPromosResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllPromos not implemented")
}
func (UnimplementedAdminServiceServer) GetAllUsers(context.Context, *GetAllUsersRequest) (*GetAllUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllUsers not implemented")
}
func (UnimplementedAdminServiceServer) BanUser(context.Context, *BanUserRequest) (*AdminResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BanUser not implemented")
}
func (UnimplementedAdminServiceServer) SendBroadcast(context.Context, *SendBroadcastRequest) (*AdminResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendBroadcast not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}
func (UnimplementedAdminServiceServer) testEmbeddedByValue()                      {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_InsertHotel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertHotelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).InsertHotel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_InsertHotel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).InsertHotel(ctx, req.(*InsertHotelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_InsertAirline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertAirlineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).InsertAirline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_InsertAirline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).InsertAirline(ctx, req.(*InsertAirlineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_CreatePromo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePromoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).CreatePromo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_CreatePromo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).CreatePromo(ctx, req.(*CreatePromoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_TogglePromoStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TogglePromoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).TogglePromoStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_TogglePromoStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).TogglePromoStatus(ctx, req.(*TogglePromoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetAllPromos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllPromosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetAllPromos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetAllPromos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetAllPromos(ctx, req.(*GetAllPromosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetAllUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetAllUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetAllUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetAllUsers(ctx, req.(*GetAllUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_BanUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BanUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).BanUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_BanUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).BanUser(ctx, req.(*BanUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_SendBroadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendBroadcastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).SendBroadcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_SendBroadcast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).SendBroadcast(ctx, req.(*SendBroadcastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "travelohi.v1.admin.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InsertHotel",
			Handler:    _AdminService_InsertHotel_Handler,
		},
		{
			MethodName: "InsertAirline",
			Handler:    _AdminService_InsertAirline_Handler,
		},
		{
			MethodName: "CreatePromo",
			Handler:    _AdminService_CreatePromo_Handler,
		},
		{
			MethodName: "TogglePromoStatus",
			Handler:    _AdminService_TogglePromoStatus_Handler,
		},
		{
			MethodName: "GetAllPromos",
			Handler:    _AdminService_GetAllPromos_Handler,
		},
		{
			MethodName: "GetAllUsers",
			Handler:    _AdminService_GetAllUsers_Handler,
		},
		{
			MethodName: "BanUser",
			Handler:    _AdminService_BanUser_Handler,
		},
		{
			MethodName: "SendBroadcast",
			Handler:    _AdminService_SendBroadcast_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/travelohi/v1/admin/admin.proto",
}
