// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: proto/travelohi/v1/admin/admin.proto

package adminpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendBroadcastRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBroadcastRequest) Reset() {
	*x = SendBroadcastRequest{}
	mi := &file_proto_travelohi_v1_admin_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBroadcastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBroadcastRequest) ProtoMessage() {}

func (x *SendBroadcastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_travelohi_v1_admin_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBroadcastRequest.ProtoReflect.Descriptor instead.
func (*SendBroadcastRequest) Descriptor() ([]byte, []int) {
	return file_proto_travelohi_v1_admin_admin_proto_rawDescGZIP(), []int{0}
}

func (x *SendBroadcastRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendBroadcastRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type InsertHotelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Pictures      [][]byte               `protobuf:"bytes,4,rep,name=pictures,proto3" json:"pictures,omitempty"`
	Facilities    []string               `protobuf:"bytes,5,rep,name=facilities,proto3" json:"facilities,omitempty"`
	StartingPrice int64                  `protobuf:"varint,6,opt,name=starting_price,json=startingPrice,proto3" json:"starting_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertHotelRequest) Reset() {
	*x = InsertHotelRequest{}
	mi := &file_proto_travelohi_v1_admin_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertHotelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertHotelRequest) ProtoMessage() {}

func (x *InsertHotelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_travelohi_v1_admin_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertHotelRequest.ProtoReflect.Descriptor instead.
func (*InsertHotelRequest) Descriptor() ([]byte, []int) {
	return file_proto_travelohi_v1_admin_admin_proto_rawDescGZIP(), []int{1}
}

func (x *InsertHotelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InsertHotelRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InsertHotelRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *InsertHotelRequest) GetPictures() [][]byte {
	if x != nil {
		return x.Pictures
	}
	return nil
}

func (x *InsertHotelRequest) GetFacilities() []string {
	if x != nil {
		return x.Facilities
	}
	return nil
}

func (x *InsertHotelRequest) GetStartingPrice() int64 {
	if x != nil {
		return x.StartingPrice
	}
	return 0
}

type InsertAirlineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IataCode      string                 `protobuf:"bytes,2,opt,name=iata_code,json=iataCode,proto3" json:"iata_code,omitempty"`
	Logo          []byte                 `protobuf:"bytes,3,opt,name=logo,proto3" json:"logo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertAirlineRequest) Reset() {
	*x = InsertAirlineRequest{}
	mi := &file_proto_travelohi_v1_admin_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertAirlineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertAirlineRequest) ProtoMessage() {}

func (x *InsertAirlineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_travelohi_v1_admin_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertAirlineRequest.ProtoReflect.Descriptor instead.
func (*InsertAirlineRequest) Descriptor() ([]byte, []int) {
	return file_proto_travelohi_v1_admin_admin_proto_rawDescGZIP(), []int{2}
}

func (x *InsertAirlineRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InsertAirlineRequest) GetIataCode() string {
	if x != nil {
		return x.IataCode
	}
	return ""
}

func (x *InsertAirlineRequest) GetLogo() []byte {
	if x != nil {
		return x.Logo
	}
	return nil
}

type CreatePromoRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PromoCode      string                 `protobuf:"bytes,1,opt,name=promo_code,json=promoCode,proto3" json:"promo_code,omitempty"`
	DiscountAmount int64                  `protobuf:"varint,2,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreatePromoRequest) Reset() {
	*x = CreatePromoRequest{}
	mi := &file_proto_travelohi_v1_admin_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePromoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePromoRequest) ProtoMessage() {}

func (x *CreatePromoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_travelohi_v1_admin_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePromoRequest.ProtoReflect.Descriptor instead.
func (*CreatePromoRequest) Descriptor() ([]byte, []int) {
	return file_proto_travelohi_v1_admin_admin_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePromoRequest) GetPromoCode() string {
	if x != nil {
		return x.PromoCode
	}
	return ""
}

func (x *CreatePromoRequest) GetDiscountAmount() int64 {
	if x != nil {
		return x.DiscountAmount
	}
	return 0
}

type TogglePromoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PromoId       string                 `protobuf:"bytes,1,opt,name=promo_id,json=promoId,proto3" json:"promo_id,omitempty"`
	IsActive      bool                   `protobuf:"varint,2,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TogglePromoRequest) Reset() {
	*x = TogglePromoRequest{}
	mi := &file_proto_travelohi_v1_admin_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TogglePromoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TogglePromoRequest) ProtoMessage() {}

func (x *TogglePromoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_travelohi_v1_admin_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TogglePromoRequest.ProtoReflect.Descriptor instead.
func (*TogglePromoRequest) Descriptor() ([]byte, []int) {
	return file_proto_travelohi_v1_admin_admin_proto_rawDescGZIP(), []int{4}
}

func (x *TogglePromoRequest) GetPromoId() string {
	if x != nil {
		return x.PromoId
	}
	return ""
}

func (x *TogglePromoRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type GetAllUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUsersRequest) Reset() {
	*x = GetAllUsersRequest{}
	mi := &file_proto_travelohi_v1_admin_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUsersRequest) ProtoMessage() {}

func (x *GetAllUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_travelohi_v1_admin_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUsersRequest.ProtoReflect.Descriptor instead.
func (*GetAllUsersRequest) Descriptor() ([]byte, []int) {
	return file_proto_travelohi_v1_admin_admin_proto_rawDescGZIP(), []int{5}
}

func (x *GetAllUsersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAllUsersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type UserAdminView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,4,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	IsBanned      bool                   `protobuf:"varint,5,opt,name=is_banned,json=isBanned,proto3" json:"is_banned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAdminView) Reset() {
	*x = UserAdminView{}
	mi := &file_proto_travelohi_v1_admin_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAdminView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAdminView) ProtoMessage() {}

func (x *UserAdminView) ProtoReflect() protoreflect.Message {
	mi := &file_proto_travelohi_v1_admin_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAdminView.ProtoReflect.Descriptor instead.
func (*UserAdminView) Descriptor() ([]byte, []int) {
	return file_proto_travelohi_v1_admin_admin_proto_rawDescGZIP(), []int{6}
}

func (x *UserAdminView) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserAdminView) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserAdminView) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *UserAdminView) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *UserAdminView) GetIsBanned() bool {
	if x != nil {
		return x.IsBanned
	}
	return false
}

type GetAllUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserAdminView       `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	TotalResults  int32                  `protobuf:"varint,2,opt,name=total_results,json=totalResults,proto3" json:"total_results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUsersResponse) Reset() {
	*x = GetAllUsersResponse{}
	mi := &file_proto_travelohi_v1_admin_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUsersResponse) ProtoMessage() {}

func (x *GetAllUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_travelohi_v1_admin_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUsersResponse.ProtoReflect.Descriptor instead.
func (*GetAllUsersResponse) Descriptor() ([]byte, []int) {
	return file_proto_travelohi_v1_admin_admin_proto_rawDescGZIP(), []int{7}
}

func (x *GetAllUsersResponse) GetUsers() []*UserAdminView {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *GetAllUsersResponse) GetTotalResults() int32 {
	if x != nil {
		return x.TotalResults
	}
	return 0
}

type BanUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BanStatus     bool                   `protobuf:"varint,2,opt,name=ban_status,json=banStatus,proto3" json:"ban_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanUserRequest) Reset() {
	*x = BanUserRequest{}
	mi := &file_proto_travelohi_v1_admin_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanUserRequest) ProtoMessage() {}

func (x *BanUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_travelohi_v1_admin_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanUserRequest.ProtoReflect.Descriptor instead.
func (*BanUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_travelohi_v1_admin_admin_proto_rawDescGZIP(), []int{8}
}

func (x *BanUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BanUserRequest) GetBanStatus() bool {
	if x != nil {
		return x.BanStatus
	}
	return false
}

type AdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminResponse) Reset() {
	*x = AdminResponse{}
	mi := &file_proto_travelohi_v1_admin_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminResponse) ProtoMessage() {}

func (x *AdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_travelohi_v1_admin_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminResponse.ProtoReflect.Descriptor instead.
func (*AdminResponse) Descriptor() ([]byte, []int) {
	return file_proto_travelohi_v1_admin_admin_proto_rawDescGZIP(), []int{9}
}

func (x *AdminResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AdminResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetAllPromosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPromosRequest) Reset() {
	*x = GetAllPromosRequest{}
	mi := &file_proto_travelohi_v1_admin_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPromosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPromosRequest) ProtoMessage() {}

func (x *GetAllPromosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_travelohi_v1_admin_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPromosRequest.ProtoReflect.Descriptor instead.
func (*GetAllPromosRequest) Descriptor() ([]byte, []int) {
	return file_proto_travelohi_v1_admin_admin_proto_rawDescGZIP(), []int{10}
}

type PromoAdminView struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PromoCode      string                 `protobuf:"bytes,2,opt,name=promo_code,json=promoCode,proto3" json:"promo_code,omitempty"`
	DiscountAmount int64                  `protobuf:"varint,3,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"`
	IsActive       bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PromoAdminView) Reset() {
	*x = PromoAdminView{}
	mi := &file_proto_travelohi_v1_admin_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromoAdminView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoAdminView) ProtoMessage() {}

func (x *PromoAdminView) ProtoReflect() protoreflect.Message {
	mi := &file_proto_travelohi_v1_admin_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoAdminView.ProtoReflect.Descriptor instead.
func (*PromoAdminView) Descriptor() ([]byte, []int) {
	return file_proto_travelohi_v1_admin_admin_proto_rawDescGZIP(), []int{11}
}

func (x *PromoAdminView) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PromoAdminView) GetPromoCode() string {
	if x != nil {
		return x.PromoCode
	}
	return ""
}

func (x *PromoAdminView) GetDiscountAmount() int64 {
	if x != nil {
		return x.DiscountAmount
	}
	return 0
}

func (x *PromoAdminView) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type GetAllPromosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Promos        []*PromoAdminView      `protobuf:"bytes,1,rep,name=promos,proto3" json:"promos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPromosResponse) Reset() {
	*x = GetAllPromosResponse{}
	mi := &file_proto_travelohi_v1_admin_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPromosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPromosResponse) ProtoMessage() {}

func (x *GetAllPromosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_travelohi_v1_admin_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPromosResponse.ProtoReflect.Descriptor instead.
func (*GetAllPromosResponse) Descriptor() ([]byte, []int) {
	return file_proto_travelohi_v1_admin_admin_proto_rawDescGZIP(), []int{12}
}

func (x *GetAllPromosResponse) GetPromos() []*PromoAdminView {
	if x != nil {
		return x.Promos
	}
	return nil
}

var File_proto_travelohi_v1_admin_admin_proto protoreflect.FileDescriptor

const file_proto_travelohi_v1_admin_admin_proto_rawDesc = "" +
	"\n" +
	"$proto/travelohi/v1/admin/admin.proto\x12\x12travelohi.v1.admin\"D\n" +
	"\x14SendBroadcastRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\"\xc7\x01\n" +
	"\x12InsertHotelRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x1a\n" +
	"\bpictures\x18\x04 \x03(\fR\bpictures\x12\x1e\n" +
	"\n" +
	"facilities\x18\x05 \x03(\tR\n" +
	"facilities\x12%\n" +
	"\x0estarting_price\x18\x06 \x01(\x03R\rstartingPrice\"[\n" +
	"\x14InsertAirlineRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tiata_code\x18\x02 \x01(\tR\biataCode\x12\x12\n" +
	"\x04logo\x18\x03 \x01(\fR\x04logo\"\\\n" +
	"\x12CreatePromoRequest\x12\x1d\n" +
	"\n" +
	"promo_code\x18\x01 \x01(\tR\tpromoCode\x12'\n" +
	"\x0fdiscount_amount\x18\x02 \x01(\x03R\x0ediscountAmount\"L\n" +
	"\x12TogglePromoRequest\x12\x19\n" +
	"\bpromo_id\x18\x01 \x01(\tR\apromoId\x12\x1b\n" +
	"\tis_active\x18\x02 \x01(\bR\bisActive\"B\n" +
	"\x12GetAllUsersRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"\x8a\x01\n" +
	"\rUserAdminView\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\x12\x19\n" +
	"\bis_admin\x18\x04 \x01(\bR\aisAdmin\x12\x1b\n" +
	"\tis_banned\x18\x05 \x01(\bR\bisBanned\"s\n" +
	"\x13GetAllUsersResponse\x127\n" +
	"\x05users\x18\x01 \x03(\v2!.travelohi.v1.admin.UserAdminViewR\x05users\x12#\n" +
	"\rtotal_results\x18\x02 \x01(\x05R\ftotalResults\"H\n" +
	"\x0eBanUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"ban_status\x18\x02 \x01(\bR\tbanStatus\"C\n" +
	"\rAdminResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x15\n" +
	"\x13GetAllPromosRequest\"\x85\x01\n" +
	"\x0ePromoAdminView\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"promo_code\x18\x02 \x01(\tR\tpromoCode\x12'\n" +
	"\x0fdiscount_amount\x18\x03 \x01(\x03R\x0ediscountAmount\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\"R\n" +
	"\x14GetAllPromosResponse\x12:\n" +
	"\x06promos\x18\x01 \x03(\v2\".travelohi.v1.admin.PromoAdminViewR\x06promos2\x83\x06\n" +
	"\fAdminService\x12Z\n" +
	"\vInsertHotel\x12&.travelohi.v1.admin.InsertHotelRequest\x1a!.travelohi.v1.admin.AdminResponse\"\x00\x12^\n" +
	"\rInsertAirline\x12(.travelohi.v1.admin.InsertAirlineRequest\x1a!.travelohi.v1.admin.AdminResponse\"\x00\x12Z\n" +
	"\vCreatePromo\x12&.travelohi.v1.admin.CreatePromoRequest\x1a!.travelohi.v1.admin.AdminResponse\"\x00\x12`\n" +
	"\x11TogglePromoStatus\x12&.travelohi.v1.admin.TogglePromoRequest\x1a!.travelohi.v1.admin.AdminResponse\"\x00\x12c\n" +
	"\fGetAllPromos\x12'.travelohi.v1.admin.GetAllPromosRequest\x1a(.travelohi.v1.admin.GetAllPromosResponse\"\x00\x12`\n" +
	"\vGetAllUsers\x12&.travelohi.v1.admin.GetAllUsersRequest\x1a'.travelohi.v1.admin.GetAllUsersResponse\"\x00\x12R\n" +
	"\aBanUser\x12\".travelohi.v1.admin.BanUserRequest\x1a!.travelohi.v1.admin.AdminResponse\"\x00\x12^\n" +
	"\rSendBroadcast\x12(.travelohi.v1.admin.SendBroadcastRequest\x1a!.travelohi.v1.admin.AdminResponse\"\x00B5Z3github.com/travelohi/backend/proto/admin/v1;adminpbb\x06proto3"

var (
	file_proto_travelohi_v1_admin_admin_proto_rawDescOnce sync.Once
	file_proto_travelohi_v1_admin_admin_proto_rawDescData []byte
)

func file_proto_travelohi_v1_admin_admin_proto_rawDescGZIP() []byte {
	file_proto_travelohi_v1_admin_admin_proto_rawDescOnce.Do(func() {
		file_proto_travelohi_v1_admin_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_travelohi_v1_admin_admin_proto_rawDesc), len(file_proto_travelohi_v1_admin_admin_proto_rawDesc)))
	})
	return file_proto_travelohi_v1_admin_admin_proto_rawDescData
}

var file_proto_travelohi_v1_admin_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_travelohi_v1_admin_admin_proto_goTypes = []any{
	(*SendBroadcastRequest)(nil), // 0: travelohi.v1.admin.SendBroadcastRequest
	(*InsertHotelRequest)(nil),   // 1: travelohi.v1.admin.InsertHotelRequest
	(*InsertAirlineRequest)(nil), // 2: travelohi.v1.admin.InsertAirlineRequest
	(*CreatePromoRequest)(nil),   // 3: travelohi.v1.admin.CreatePromoRequest
	(*TogglePromoRequest)(nil),   // 4: travelohi.v1.admin.TogglePromoRequest
	(*GetAllUsersRequest)(nil),   // 5: travelohi.v1.admin.GetAllUsersRequest
	(*UserAdminView)(nil),        // 6: travelohi.v1.admin.UserAdminView
	(*GetAllUsersResponse)(nil),  // 7: travelohi.v1.admin.GetAllUsersResponse
	(*BanUserRequest)(nil),       // 8: travelohi.v1.admin.BanUserRequest
	(*AdminResponse)(nil),        // 9: travelohi.v1.admin.AdminResponse
	(*GetAllPromosRequest)(nil),  // 10: travelohi.v1.admin.GetAllPromosRequest
	(*PromoAdminView)(nil),       // 11: travelohi.v1.admin.PromoAdminView
	(*GetAllPromosResponse)(nil), // 12: travelohi.v1.admin.GetAllPromosResponse
}
var file_proto_travelohi_v1_admin_admin_proto_depIdxs = []int32{
	6,  // 0: travelohi.v1.admin.GetAllUsersResponse.users:type_name -> travelohi.v1.admin.UserAdminView
	11, // 1: travelohi.v1.admin.GetAllPromosResponse.promos:type_name -> travelohi.v1.admin.PromoAdminView
	1,  // 2: travelohi.v1.admin.AdminService.InsertHotel:input_type -> travelohi.v1.admin.InsertHotelRequest
	2,  // 3: travelohi.v1.admin.AdminService.InsertAirline:input_type -> travelohi.v1.admin.InsertAirlineRequest
	3,  // 4: travelohi.v1.admin.AdminService.CreatePromo:input_type -> travelohi.v1.admin.CreatePromoRequest
	4,  // 5: travelohi.v1.admin.AdminService.TogglePromoStatus:input_type -> travelohi.v1.admin.TogglePromoRequest
	10, // 6: travelohi.v1.admin.AdminService.GetAllPromos:input_type -> travelohi.v1.admin.GetAllPromosRequest
	5,  // 7: travelohi.v1.admin.AdminService.GetAllUsers:input_type -> travelohi.v1.admin.GetAllUsersRequest
	8,  // 8: travelohi.v1.admin.AdminService.BanUser:input_type -> travelohi.v1.admin.BanUserRequest
	0,  // 9: travelohi.v1.admin.AdminService.SendBroadcast:input_type -> travelohi.v1.admin.SendBroadcastRequest
	9,  // 10: travelohi.v1.admin.AdminService.InsertHotel:output_type -> travelohi.v1.admin.AdminResponse
	9,  // 11: travelohi.v1.admin.AdminService.InsertAirline:output_type -> travelohi.v1.admin.AdminResponse
	9,  // 12: travelohi.v1.admin.AdminService.CreatePromo:output_type -> travelohi.v1.admin.AdminResponse
	9,  // 13: travelohi.v1.admin.AdminService.TogglePromoStatus:output_type -> travelohi.v1.admin.AdminResponse
	12, // 14: travelohi.v1.admin.AdminService.GetAllPromos:output_type -> travelohi.v1.admin.GetAllPromosResponse
	7,  // 15: travelohi.v1.admin.AdminService.GetAllUsers:output_type -> travelohi.v1.admin.GetAllUsersResponse
	9,  // 16: travelohi.v1.admin.AdminService.BanUser:output_type -> travelohi.v1.admin.AdminResponse
	9,  // 17: travelohi.v1.admin.AdminService.SendBroadcast:output_type -> travelohi.v1.admin.AdminResponse
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_travelohi_v1_admin_admin_proto_init() }
func file_proto_travelohi_v1_admin_admin_proto_init() {
	if File_proto_travelohi_v1_admin_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_travelohi_v1_admin_admin_proto_rawDesc), len(file_proto_travelohi_v1_admin_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_travelohi_v1_admin_admin_proto_goTypes,
		DependencyIndexes: file_proto_travelohi_v1_admin_admin_proto_depIdxs,
		MessageInfos:      file_proto_travelohi_v1_admin_admin_proto_msgTypes,
	}.Build()
	File_proto_travelohi_v1_admin_admin_proto = out.File
	file_proto_travelohi_v1_admin_admin_proto_goTypes = nil
	file_proto_travelohi_v1_admin_admin_proto_depIdxs = nil
}
